use std::{
    collections::BTreeMap,
    env, fs,
    path::{Path, PathBuf},
    process::{Command, Stdio},
    time::{Duration, Instant},
};

mod cardano_transcript;

use cardano_transcript::{CardanoBlake2bRead, CardanoBlake2bWrite};
use frost::{Ciphersuite, Identifier};
use frost_secp256k1_tr as frost;
use halo2_base::halo2_proofs::{
    halo2curves::{
        bls12_381::{Bls12, Fr as BlsFr, G1Affine},
        ff::PrimeField,
        secp256k1::Fq,
    },
    plonk::{Circuit, ProvingKey, create_proof, keygen_pk, keygen_vk, verify_proof},
    poly::{
        commitment::ParamsProver,
        kzg::{
            commitment::{KZGCommitmentScheme, ParamsKZG},
            multiopen::{ProverSHPLONK, VerifierSHPLONK},
            strategy::SingleStrategy,
        },
    },
    transcript::{Challenge255, TranscriptReadBuffer, TranscriptWriterBuffer},
};
use k256::{
    AffinePoint, EncodedPoint, ProjectivePoint, Scalar,
    elliptic_curve::sec1::{FromEncodedPoint, ToEncodedPoint},
};
use pallas_crypto::key::ed25519;
use plutus_halo2_verifier_gen::plutus_gen::{
    AxiomShplonkAikenOutputPaths, generate_axiom_shplonk_aiken_from_vk_and_instances,
};
use rand::{SeedableRng, rngs::StdRng};
use rand_chacha::ChaCha20Rng;
use serde_json::Value;

use heimdall::circuits::dkg_fault::{
    AxiomDkgCircuitParams, CircuitStats, DkgRound1PokDigestFaultWitness,
    DkgRound2ShareFaultWitness, axiom_point_from_compressed, axiom_point_from_projective,
    axiom_scalar_from_be_bytes, build_round1_digest_fault_keygen_circuit,
    build_round1_digest_fault_prover_circuit, build_round2_digest_fault_keygen_circuit,
    build_round2_digest_fault_prover_circuit, is_identity, round1_digest_residual,
    round1_hdk_challenge, round1_message_digest, round2_message_digest, round2_residual,
};
use heimdall::frost::participant;

const ROUND2_T: usize = 2;
const ROUND2_INDEX_BITS: usize = 16;
const TARGET_ROOT: &str = "target/dkg_fault_onchain";
const DEFAULT_MAX_TX_EX_MEM: u64 = 16_500_000;
const DEFAULT_MAX_TX_EX_CPU: u64 = 10_000_000_000;
const GENERATE_ONLY_ENV: &str = "DKG_FAULT_ONCHAIN_GENERATE_ONLY";
const AIKEN_TOML: &str = r#"name = "heimdall/dkg_fault_onchain_benchmark"
version = "0.0.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Generated DKG fault proof on-chain benchmark project"

[repository]
user = "heimdall"
project = "dkg_fault_onchain_benchmark"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2.2.0"
source = "github"

[config.default]
network_id = 1
"#;
const AIKEN_LOCK: &str = r#"# This file was generated by Aiken
# You typically do not need to edit this file

[[requirements]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[[requirements]]
name = "aiken-lang/fuzz"
version = "v2.2.0"
source = "github"

[[packages]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
requirements = []
source = "github"

[[packages]]
name = "aiken-lang/fuzz"
version = "v2.2.0"
requirements = []
source = "github"

[etags]
"#;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum RunMode {
    Benchmark,
    GenerateOnly,
}

fn main() {
    let mode = run_mode();
    let limits = tx_ex_unit_limits();
    println!(
        "backend: Axiom halo2-axiom, BLS12-381 KZG, SHPLONK, Cardano-friendly Blake2b transcript"
    );
    println!(
        "onchain_benchmark: Aiken Plutus V3 minting policy with two pubkey inputs and two pubkey outputs"
    );
    println!("mode: {mode:?}");
    println!("max_tx_ex_units_mem: {}", limits.mem);
    println!("max_tx_ex_units_cpu: {}", limits.cpu);

    let reports = match env::var("DKG_FAULT_ONCHAIN_ROUND").as_deref() {
        Ok("round1") => vec![run_round1_onchain(
            AxiomDkgCircuitParams::round1_digest_fault(),
            mode,
        )],
        Ok("round2") => vec![run_round2_onchain(
            AxiomDkgCircuitParams::round2_digest_fault(),
            mode,
        )],
        Ok("all") | Err(_) => vec![
            run_round1_onchain(AxiomDkgCircuitParams::round1_digest_fault(), mode),
            run_round2_onchain(AxiomDkgCircuitParams::round2_digest_fault(), mode),
        ],
        Ok(other) => panic!("DKG_FAULT_ONCHAIN_ROUND must be round1, round2, or all; got {other}"),
    }
    .into_iter()
    .flatten()
    .collect::<Vec<_>>();

    if mode == RunMode::Benchmark {
        assert_all_within_tx_budget(&reports, limits);
    }
}

fn run_mode() -> RunMode {
    let generate_only = env::var(GENERATE_ONLY_ENV)
        .map(|value| matches!(value.as_str(), "1" | "true" | "TRUE" | "yes" | "YES"))
        .unwrap_or(false);
    if generate_only {
        RunMode::GenerateOnly
    } else {
        RunMode::Benchmark
    }
}

fn run_round1_onchain(params: AxiomDkgCircuitParams, mode: RunMode) -> Option<BudgetReport> {
    let cases = round1_fixtures();
    let corrupted = cases
        .iter()
        .find(|case| !case.expect_residual_matches_transcript)
        .expect("round 1 corrupted fixture")
        .clone();
    let honest = cases
        .iter()
        .find(|case| case.expect_residual_matches_transcript)
        .expect("round 1 honest fixture")
        .clone();

    let (keygen_builder, stats) =
        build_round1_digest_fault_keygen_circuit(params, &corrupted.witness);
    let setup = setup(params);
    let (pk, break_points, keygen_times) = keygen(&setup, keygen_builder);

    println!();
    println!("== round1-onchain-pok-digest-fault ==");
    print_circuit_config(params);
    print_stats(&stats, params);
    print_keygen_times(&keygen_times);

    let corrupted_artifact = prove_round1_digest_fault_case(
        &setup,
        &pk,
        stats.config_params.clone(),
        break_points,
        params,
        &corrupted,
    );
    let honest_digest = round1_message_digest(params, &honest.witness);
    let honest_artifact = corrupted_artifact.with_digest("round1-honest-digest", honest_digest);
    print_digest_proof_artifact(&corrupted_artifact);

    let project_dir =
        generate_digest_project("round1", &setup, &pk, &corrupted_artifact, &honest_artifact);
    print_generated_project(&project_dir);
    if mode == RunMode::GenerateOnly {
        return None;
    }

    let aiken_start = Instant::now();
    let aiken_output = run_aiken_check(&project_dir);
    let aiken_time = aiken_start.elapsed();
    let budget = parse_aiken_budget(&aiken_output, "round1_corrupted_mint_benchmark")
        .expect("round 1 Aiken benchmark ExUnits should be present");
    print_onchain_budget("round1_corrupted_mint_benchmark", budget, aiken_time);
    Some(BudgetReport {
        name: "round1_corrupted_mint_benchmark",
        budget,
    })
}

fn run_round2_onchain(params: AxiomDkgCircuitParams, mode: RunMode) -> Option<BudgetReport> {
    let cases = round2_fixtures();
    let corrupted = cases
        .iter()
        .find(|case| !case.expect_identity_residual)
        .expect("round 2 corrupted fixture")
        .clone();
    let honest = cases
        .iter()
        .find(|case| case.expect_identity_residual)
        .expect("round 2 honest fixture")
        .clone();

    let (keygen_builder, stats) = build_round2_digest_fault_keygen_circuit::<
        ROUND2_T,
        ROUND2_INDEX_BITS,
    >(params, &corrupted.witness);
    let setup = setup(params);
    let (pk, break_points, keygen_times) = keygen(&setup, keygen_builder);

    println!();
    println!("== round2-onchain-share-digest-fault ==");
    print_circuit_config(params);
    print_stats(&stats, params);
    print_keygen_times(&keygen_times);

    let corrupted_artifact = prove_round2_digest_fault_case(
        &setup,
        &pk,
        stats.config_params.clone(),
        break_points,
        params,
        &corrupted,
    );
    let honest_digest =
        round2_message_digest::<ROUND2_T, ROUND2_INDEX_BITS>(params, &honest.witness);
    let honest_artifact = corrupted_artifact.with_digest("round2-honest-digest", honest_digest);
    print_digest_proof_artifact(&corrupted_artifact);

    let project_dir =
        generate_digest_project("round2", &setup, &pk, &corrupted_artifact, &honest_artifact);
    print_generated_project(&project_dir);
    if mode == RunMode::GenerateOnly {
        return None;
    }

    let aiken_start = Instant::now();
    let aiken_output = run_aiken_check(&project_dir);
    let aiken_time = aiken_start.elapsed();
    let budget = parse_aiken_budget(&aiken_output, "round2_corrupted_mint_benchmark")
        .expect("round 2 Aiken benchmark ExUnits should be present");
    print_onchain_budget("round2_corrupted_mint_benchmark", budget, aiken_time);
    Some(BudgetReport {
        name: "round2_corrupted_mint_benchmark",
        budget,
    })
}

fn setup(params: AxiomDkgCircuitParams) -> ParamsKZG<Bls12> {
    ParamsKZG::<Bls12>::setup(params.degree, StdRng::seed_from_u64(2))
}

fn keygen(
    setup: &ParamsKZG<Bls12>,
    keygen_builder: halo2_base::gates::circuit::builder::RangeCircuitBuilder<BlsFr>,
) -> (ProvingKey<G1Affine>, Vec<Vec<usize>>, KeygenTimes) {
    let vk_start = Instant::now();
    let vk = keygen_vk(setup, &keygen_builder).expect("vkey generation should succeed");
    let vk_time = vk_start.elapsed();

    let pk_start = Instant::now();
    let pk = keygen_pk(setup, vk, &keygen_builder).expect("pkey generation should succeed");
    let pk_time = pk_start.elapsed();

    let break_points = keygen_builder.break_points();
    (pk, break_points, KeygenTimes { vk_time, pk_time })
}

fn prove_round1_digest_fault_case(
    setup: &ParamsKZG<Bls12>,
    pk: &ProvingKey<G1Affine>,
    config_params: halo2_base::gates::circuit::BaseCircuitParams,
    break_points: Vec<Vec<usize>>,
    params: AxiomDkgCircuitParams,
    case: &Round1Case,
) -> DigestProofArtifact {
    let witness_start = Instant::now();
    let (prover_builder, public_instances) = build_round1_digest_fault_prover_circuit(
        config_params,
        break_points,
        params,
        &case.witness,
    );
    let witness_time = witness_start.elapsed();

    let expected_digest = round1_message_digest(params, &case.witness);
    assert_eq!(public_instances, vec![expected_digest]);
    assert_eq!(case.witness.challenge, round1_hdk_challenge(&case.witness));
    let computed = round1_digest_residual(&case.witness);
    assert_eq!(
        computed == case.witness.transcript_r,
        case.expect_residual_matches_transcript
    );
    assert!(!case.expect_residual_matches_transcript);

    prove_digest_artifact(
        setup,
        pk,
        prover_builder,
        public_instances,
        expected_digest,
        case.name.clone(),
        witness_time,
        "public input = signed Poseidon(message), circuit derives HDKG and asserts D != R",
    )
}

fn prove_round2_digest_fault_case(
    setup: &ParamsKZG<Bls12>,
    pk: &ProvingKey<G1Affine>,
    config_params: halo2_base::gates::circuit::BaseCircuitParams,
    break_points: Vec<Vec<usize>>,
    params: AxiomDkgCircuitParams,
    case: &Round2Case,
) -> DigestProofArtifact {
    let witness_start = Instant::now();
    let (prover_builder, public_instances) = build_round2_digest_fault_prover_circuit::<
        ROUND2_T,
        ROUND2_INDEX_BITS,
    >(
        config_params, break_points, params, &case.witness
    );
    let witness_time = witness_start.elapsed();

    let expected_digest =
        round2_message_digest::<ROUND2_T, ROUND2_INDEX_BITS>(params, &case.witness);
    assert_eq!(public_instances, vec![expected_digest]);
    let computed = round2_residual(&case.witness);
    assert!(!is_identity(&computed));

    prove_digest_artifact(
        setup,
        pk,
        prover_builder,
        public_instances,
        expected_digest,
        case.name.clone(),
        witness_time,
        "public input = signed Poseidon(message), circuit asserts D != identity",
    )
}

fn prove_digest_artifact<C>(
    setup: &ParamsKZG<Bls12>,
    pk: &ProvingKey<G1Affine>,
    circuit: C,
    public_instances: Vec<BlsFr>,
    digest: BlsFr,
    name: String,
    witness_time: Duration,
    host_check: &'static str,
) -> DigestProofArtifact
where
    C: Circuit<BlsFr>,
{
    let proof_start = Instant::now();
    let proof = gen_proof(setup, pk, circuit, &public_instances);
    let proof_time = proof_start.elapsed();

    let verify_start = Instant::now();
    verify(setup, pk, &proof, &public_instances);
    let verify_time = verify_start.elapsed();

    let (spo_vkey, spo_sig) = sign_digest(digest);
    DigestProofArtifact {
        name,
        proof,
        public_instances,
        digest,
        spo_vkey,
        spo_sig,
        host_check,
        witness_time,
        proof_time,
        verify_time,
    }
}

fn gen_proof<C>(
    params: &ParamsKZG<Bls12>,
    pk: &ProvingKey<G1Affine>,
    circuit: C,
    public_instances: &[BlsFr],
) -> Vec<u8>
where
    C: Circuit<BlsFr>,
{
    let rng = StdRng::seed_from_u64(1);
    let instances: &[&[BlsFr]] = &[public_instances];
    let mut transcript = CardanoBlake2bWrite::<_, G1Affine>::init(vec![]);
    create_proof::<
        KZGCommitmentScheme<Bls12>,
        ProverSHPLONK<'_, Bls12>,
        Challenge255<_>,
        _,
        CardanoBlake2bWrite<Vec<u8>, G1Affine>,
        _,
    >(params, pk, &[circuit], &[instances], rng, &mut transcript)
    .expect("proof generation should succeed");
    transcript.finalize()
}

fn verify(
    params: &ParamsKZG<Bls12>,
    pk: &ProvingKey<G1Affine>,
    proof: &[u8],
    public_instances: &[BlsFr],
) {
    let verifier_params = params.verifier_params();
    let strategy = SingleStrategy::new(params);
    let instances: &[&[BlsFr]] = &[public_instances];
    let mut transcript = CardanoBlake2bRead::<_, G1Affine>::init(proof);
    verify_proof::<
        KZGCommitmentScheme<Bls12>,
        VerifierSHPLONK<'_, Bls12>,
        Challenge255<G1Affine>,
        CardanoBlake2bRead<&[u8], G1Affine>,
        SingleStrategy<'_, Bls12>,
    >(
        verifier_params,
        pk.get_vk(),
        strategy,
        &[instances],
        &mut transcript,
    )
    .expect("proof verification should succeed");
}

fn generate_digest_project(
    round_name: &str,
    setup: &ParamsKZG<Bls12>,
    pk: &ProvingKey<G1Affine>,
    corrupted: &DigestProofArtifact,
    honest: &DigestProofArtifact,
) -> PathBuf {
    let project_dir = prepare_project(round_name);
    let paths = generator_paths(&project_dir);

    let generator_start = Instant::now();
    generate_axiom_shplonk_aiken_from_vk_and_instances(
        setup,
        pk.get_vk(),
        &corrupted.proof,
        &[corrupted.public_instances.as_slice()],
        &paths,
    )
    .expect("Axiom SHPLONK verifier generation should succeed");
    println!(
        "{round_name}_generic_generator_time: {}",
        fmt_duration(generator_start.elapsed())
    );

    write_digest_policy(&project_dir, round_name, corrupted, honest);
    project_dir
}

fn print_generated_project(project_dir: &Path) {
    println!("generated_aiken_project: {}", project_dir.display());
    println!(
        "generated_plutus_blueprint_command: cd {} && aiken build",
        project_dir.display()
    );
}

fn prepare_project(round_name: &str) -> PathBuf {
    let project_dir = Path::new(TARGET_ROOT).join(round_name);
    if project_dir.exists() {
        fs::remove_dir_all(&project_dir).expect("remove stale generated Aiken project");
    }
    fs::create_dir_all(project_dir.join("lib")).expect("create generated Aiken lib dir");
    fs::create_dir_all(project_dir.join("validators")).expect("create validator output dir");
    fs::write(project_dir.join("aiken.toml"), AIKEN_TOML).expect("write generated Aiken manifest");
    fs::write(project_dir.join("aiken.lock"), AIKEN_LOCK).expect("write generated Aiken lock file");
    project_dir
}

fn generator_paths(project_dir: &Path) -> AxiomShplonkAikenOutputPaths {
    let support_dir = project_dir.join("lib");
    AxiomShplonkAikenOutputPaths {
        verifier_output: support_dir.join("proof_verifier.ak"),
        verifier_key_output: support_dir.join("verifier_key.ak"),
        support_dir,
    }
}

fn write_digest_policy(
    project_dir: &Path,
    round_name: &str,
    corrupted: &DigestProofArtifact,
    honest: &DigestProofArtifact,
) {
    let policy = digest_policy_source(round_name, corrupted, honest);
    fs::write(
        project_dir.join("validators").join("dkg_fault_mint.ak"),
        policy,
    )
    .expect("write generated digest DKG fault mint policy");

    let tests_dir = project_dir.join("validators").join("tests");
    fs::create_dir_all(&tests_dir).expect("create generated validator tests dir");
    let tests = digest_policy_tests_source(round_name, corrupted, honest);
    fs::write(tests_dir.join("dkg_fault_mint.ak"), tests)
        .expect("write generated digest DKG fault mint policy tests");
}

fn digest_policy_source(
    round_name: &str,
    corrupted: &DigestProofArtifact,
    honest: &DigestProofArtifact,
) -> String {
    let policy_id = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b";
    let benchmark_name = format!("{round_name}_corrupted_mint_benchmark");
    let reject_name = format!("{round_name}_honest_mint_rejected");

    let mut source = r#"use aiken/collection/dict
use aiken/collection/list
use aiken/crypto.{blake2b_224, blake2b_256, verify_ed25519_signature}
use aiken/crypto/bls12_381/scalar.{from_bytes_little_endian}
use aiken/primitive/bytearray
use cardano/address
use cardano/assets
use cardano/assets.{PolicyId, quantity_of, tokens}
use cardano/transaction.{
  Input, NoDatum, Output, OutputReference, Transaction, placeholder,
}
use proof_verifier.{verifier}

pub type FaultRedeemer {
  proof: ByteArray,
  digest: ByteArray,
  spo_vkey: ByteArray,
  spo_sig: ByteArray,
}

validator dkg_fault_mint {
  mint(redeemer: FaultRedeemer, policy_id: PolicyId, self: Transaction) {
    validate_fault(redeemer, policy_id, self)
  }

  else(_) {
    fail
  }
}

pub fn validate_fault(
  redeemer: FaultRedeemer,
  policy_id: PolicyId,
  self: Transaction,
) -> Bool {
  let public_inputs = [from_bytes_little_endian(redeemer.digest)]
  let token_name = fault_token_name(redeemer.spo_vkey, redeemer.digest)
  expect [Pair(minted_token_name, 1)] =
    dict.to_pairs(tokens(self.mint, policy_id))
  and {
    minted_token_name == token_name,
    verify_ed25519_signature(redeemer.spo_vkey, redeemer.digest, redeemer.spo_sig),
    verifier(redeemer.proof, public_inputs),
    output_contains_token(self, policy_id, token_name),
    list.length(self.inputs) == 2,
    list.length(self.outputs) == 2,
  }
}

pub fn fault_token_name(spo_vkey: ByteArray, public_input: ByteArray) -> ByteArray {
  let pool_id = blake2b_224(spo_vkey)
  blake2b_256(bytearray.concat(pool_id, public_input))
}

fn output_contains_token(
  self: Transaction,
  policy_id: PolicyId,
  token_name: ByteArray,
) -> Bool {
  list.any(
    self.outputs,
    fn(output) { quantity_of(output.value, policy_id, token_name) == 1 },
  )
}

const policy_id =
  #"__POLICY_ID__"

const corrupted_proof =
  #"__CORRUPTED_PROOF__"

const corrupted_digest =
  #"__CORRUPTED_DIGEST__"

const corrupted_spo_vkey =
  #"__CORRUPTED_SPO_VKEY__"

const corrupted_spo_sig =
  #"__CORRUPTED_SPO_SIG__"

const honest_proof =
  #"__HONEST_PROOF__"

const honest_digest =
  #"__HONEST_DIGEST__"

const honest_spo_vkey =
  #"__HONEST_SPO_VKEY__"

const honest_spo_sig =
  #"__HONEST_SPO_SIG__"

fn corrupted_redeemer() -> FaultRedeemer {
  FaultRedeemer {
    proof: corrupted_proof,
    digest: corrupted_digest,
    spo_vkey: corrupted_spo_vkey,
    spo_sig: corrupted_spo_sig,
  }
}

fn honest_redeemer() -> FaultRedeemer {
  FaultRedeemer {
    proof: honest_proof,
    digest: honest_digest,
    spo_vkey: honest_spo_vkey,
    spo_sig: honest_spo_sig,
  }
}

fn test_address() {
  address.from_verification_key(
    #"101112131415161718191a1b1c1d1e1f202122232425262728292a2b",
  )
}

fn output(value) -> Output {
  Output {
    address: test_address(),
    value,
    datum: NoDatum,
    reference_script: None,
  }
}

fn input(index: Int) -> Input {
  Input {
    output_reference: OutputReference {
      transaction_id: #"202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f",
      output_index: index,
    },
    output: output(assets.from_lovelace(2_000_000)),
  }
}

fn tx(redeemer: FaultRedeemer) -> Transaction {
  let token_name = fault_token_name(redeemer.spo_vkey, redeemer.digest)
  let token_output_value =
    assets.from_lovelace(1_500_000)
      |> assets.add(policy_id, token_name, 1)

  Transaction {
    ..placeholder,
    inputs: [input(0), input(1)],
    outputs: [
      output(token_output_value),
      output(assets.from_lovelace(2_000_000)),
    ],
    fee: 200_000,
    mint: assets.from_asset(policy_id, token_name, 1),
    redeemers: [],
  }
}

test __BENCHMARK_NAME__() {
  let redeemer = corrupted_redeemer()
  dkg_fault_mint.mint(redeemer, policy_id, tx(redeemer))
}

test __REJECT_NAME__() fail {
  let redeemer = honest_redeemer()
  dkg_fault_mint.mint(redeemer, policy_id, tx(redeemer))
}
"#
    .to_string();

    let replacements = [
        ("__POLICY_ID__", policy_id.to_string()),
        ("__CORRUPTED_PROOF__", hex::encode(&corrupted.proof)),
        ("__CORRUPTED_DIGEST__", bls_scalar_hex(corrupted.digest)),
        ("__CORRUPTED_SPO_VKEY__", hex::encode(corrupted.spo_vkey)),
        ("__CORRUPTED_SPO_SIG__", hex::encode(corrupted.spo_sig)),
        ("__HONEST_PROOF__", hex::encode(&honest.proof)),
        ("__HONEST_DIGEST__", bls_scalar_hex(honest.digest)),
        ("__HONEST_SPO_VKEY__", hex::encode(honest.spo_vkey)),
        ("__HONEST_SPO_SIG__", hex::encode(honest.spo_sig)),
        ("__BENCHMARK_NAME__", benchmark_name),
        ("__REJECT_NAME__", reject_name),
    ];

    for (placeholder, value) in replacements {
        source = source.replace(placeholder, &value);
    }
    source
}

fn digest_policy_tests_source(
    round_name: &str,
    corrupted: &DigestProofArtifact,
    honest: &DigestProofArtifact,
) -> String {
    let policy = digest_policy_source(round_name, corrupted, honest);
    let (_, fixtures) = policy
        .split_once("const policy_id")
        .expect("generated policy contains fixture constants");
    let fixtures = format!("const policy_id{fixtures}")
        .replace("dkg_fault_mint.mint", "dkg_fault_mint.dkg_fault_mint.mint");

    format!(
        r#"use cardano/address
use cardano/assets
use cardano/transaction.{{Input, NoDatum, Output, OutputReference, Transaction, placeholder}}
use dkg_fault_mint
use dkg_fault_mint.{{FaultRedeemer, fault_token_name}}

{fixtures}"#
    )
}

fn bls_scalar_hex(scalar: BlsFr) -> String {
    hex::encode(scalar.to_repr())
}

fn sign_digest(digest: BlsFr) -> ([u8; 32], [u8; 64]) {
    let key = ed25519::SecretKey::from([0x42; 32]);
    let message = digest.to_repr();
    let vkey: [u8; 32] = key.public_key().into();
    let sig: [u8; 64] = key
        .sign(message)
        .as_ref()
        .try_into()
        .expect("ed25519 signature is 64 bytes");
    (vkey, sig)
}

fn run_aiken_check(project_dir: &Path) -> String {
    let output = Command::new("aiken")
        .arg("check")
        .arg("--deny")
        .arg("--match-tests")
        .arg("tests/dkg_fault_mint")
        .arg(".")
        .current_dir(project_dir)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .expect("aiken check should start");

    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);

    if !output.status.success() {
        print!("{stdout}");
        eprint!("{stderr}");
    } else if !stderr.trim().is_empty() {
        eprint!("{stderr}");
    }
    assert!(output.status.success(), "aiken check should pass");
    stdout.into_owned()
}

fn parse_aiken_budget(output: &str, benchmark_name: &str) -> Option<ExUnits> {
    if let Some(budget) = parse_aiken_json_budget(output, benchmark_name) {
        return Some(budget);
    }

    let lines: Vec<_> = output.lines().collect();
    for (idx, line) in lines.iter().enumerate() {
        if !line.contains(benchmark_name) {
            continue;
        }

        let window = lines[idx..lines.len().min(idx + 8)].join(" ");
        let mem = parse_metric(&window, "mem:")?.replace('_', "");
        let cpu = parse_metric(&window, "cpu:")?.replace('_', "");
        return Some(ExUnits {
            mem: mem.parse().ok()?,
            cpu: cpu.parse().ok()?,
        });
    }
    None
}

fn parse_aiken_json_budget(output: &str, benchmark_name: &str) -> Option<ExUnits> {
    let json: Value = serde_json::from_str(output).ok()?;
    let modules = json.get("modules")?.as_array()?;
    for module in modules {
        let tests = module.get("tests")?.as_array()?;
        for test in tests {
            if test.get("title")?.as_str()? != benchmark_name {
                continue;
            }

            let execution_units = test.get("execution_units")?;
            return Some(ExUnits {
                mem: execution_units.get("mem")?.as_u64()?,
                cpu: execution_units.get("cpu")?.as_u64()?,
            });
        }
    }
    None
}

fn parse_metric(text: &str, label: &str) -> Option<String> {
    let after = text.split(label).nth(1)?;
    let value: String = after
        .chars()
        .skip_while(|char| char.is_whitespace())
        .take_while(|char| char.is_ascii_digit() || *char == '_')
        .collect();
    (!value.is_empty()).then_some(value)
}

fn tx_ex_unit_limits() -> ExUnits {
    ExUnits {
        mem: env_u64("DKG_FAULT_MAX_TX_EX_MEM").unwrap_or(DEFAULT_MAX_TX_EX_MEM),
        cpu: env_u64("DKG_FAULT_MAX_TX_EX_CPU").unwrap_or(DEFAULT_MAX_TX_EX_CPU),
    }
}

fn env_u64(name: &str) -> Option<u64> {
    let value = env::var(name).ok()?;
    Some(
        value
            .parse()
            .unwrap_or_else(|err| panic!("{name} must be an unsigned integer: {err}")),
    )
}

fn assert_all_within_tx_budget(reports: &[BudgetReport], limits: ExUnits) {
    let violations = reports
        .iter()
        .filter(|report| report.budget.mem > limits.mem || report.budget.cpu > limits.cpu)
        .map(|report| {
            format!(
                "{}: mem={} cpu={} limits_mem={} limits_cpu={}",
                report.name, report.budget.mem, report.budget.cpu, limits.mem, limits.cpu
            )
        })
        .collect::<Vec<_>>();

    assert!(
        violations.is_empty(),
        "on-chain DKG fault benchmarks exceed transaction ExUnit limits:\n{}",
        violations.join("\n")
    );
}

fn print_stats(stats: &CircuitStats, params: AxiomDkgCircuitParams) {
    println!(
        "shape: k={}, usable_rows={}, advice={:?}, lookup_advice={:?}, fixed={}, lookup_bits={:?}",
        stats.config_params.k,
        (1usize << stats.config_params.k) - params.unusable_rows,
        stats.config_params.num_advice_per_phase,
        stats.config_params.num_lookup_advice_per_phase,
        stats.config_params.num_fixed,
        stats.config_params.lookup_bits
    );
    println!("total_advice_cells: {}", stats.total_advice_cells);
    println!(
        "enabled_gate_constraints: {}",
        stats.enabled_gate_constraints
    );
    println!("total_lookup_cells: {}", stats.total_lookup_cells);
    println!("total_fixed_cells: {}", stats.total_fixed_cells);
}

fn print_keygen_times(times: &KeygenTimes) {
    println!("vk_time: {}", fmt_duration(times.vk_time));
    println!("pk_time: {}", fmt_duration(times.pk_time));
}

fn print_digest_proof_artifact(artifact: &DigestProofArtifact) {
    println!("case: {}", artifact.name);
    println!(
        "  public_instance_count: {}",
        artifact.public_instances.len()
    );
    println!("  proof_size_bytes: {}", artifact.proof.len());
    println!("  witness_time: {}", fmt_duration(artifact.witness_time));
    println!("  proof_time: {}", fmt_duration(artifact.proof_time));
    println!("  verify_time: {}", fmt_duration(artifact.verify_time));
    println!("  host_check: {}", artifact.host_check);
}

fn print_circuit_config(params: AxiomDkgCircuitParams) {
    println!(
        "circuit_config: k={}, lookup_bits={}, advice_columns={}, lookup_advice_columns={}, fixed_columns={}, limb_bits={}, num_limbs={}, window_bits={}, unusable_rows={}",
        params.degree,
        params.lookup_bits,
        params.advice_columns,
        params.lookup_advice_columns,
        params.fixed_columns,
        params.limb_bits,
        params.num_limbs,
        params.window_bits,
        params.unusable_rows
    );
}

fn print_onchain_budget(name: &str, budget: ExUnits, aiken_time: Duration) {
    println!("aiken_benchmark: {name}");
    println!("aiken_mem: {}", budget.mem);
    println!("aiken_cpu: {}", budget.cpu);
    println!("aiken_check_time: {}", fmt_duration(aiken_time));
}

fn fmt_duration(duration: Duration) -> String {
    format!("{:.3}s", duration.as_secs_f64())
}

#[derive(Clone, Copy)]
struct KeygenTimes {
    vk_time: Duration,
    pk_time: Duration,
}

#[derive(Clone)]
struct DigestProofArtifact {
    name: String,
    proof: Vec<u8>,
    public_instances: Vec<BlsFr>,
    digest: BlsFr,
    spo_vkey: [u8; 32],
    spo_sig: [u8; 64],
    host_check: &'static str,
    witness_time: Duration,
    proof_time: Duration,
    verify_time: Duration,
}

impl DigestProofArtifact {
    fn with_digest(&self, name: &str, digest: BlsFr) -> Self {
        let (spo_vkey, spo_sig) = sign_digest(digest);
        Self {
            name: name.to_string(),
            proof: self.proof.clone(),
            public_instances: vec![digest],
            digest,
            spo_vkey,
            spo_sig,
            host_check: "signed digest does not match proof public input",
            witness_time: Duration::ZERO,
            proof_time: Duration::ZERO,
            verify_time: Duration::ZERO,
        }
    }
}

#[derive(Clone, Copy)]
struct ExUnits {
    mem: u64,
    cpu: u64,
}

struct BudgetReport {
    name: &'static str,
    budget: ExUnits,
}

#[derive(Clone)]
struct Round1Case {
    name: String,
    witness: DkgRound1PokDigestFaultWitness,
    expect_residual_matches_transcript: bool,
}

#[derive(Clone)]
struct Round2Case {
    name: String,
    witness: DkgRound2ShareFaultWitness,
    expect_identity_residual: bool,
}

fn round1_fixtures() -> Vec<Round1Case> {
    let mut rng = ChaCha20Rng::seed_from_u64(0x524f_554e_4431);
    let participant_identifier = 1u16;
    let identifier = Identifier::try_from(participant_identifier).unwrap();
    let (_secret, package) = participant::dkg_part1(identifier, 3, 2, &mut rng).unwrap();

    let commitments = package.commitment().serialize().unwrap();
    let phi0_bytes: [u8; 33] = commitments[0].as_slice().try_into().unwrap();
    let phi0 = axiom_point_from_compressed(&phi0_bytes);

    let proof_bytes = package.proof_of_knowledge().serialize().unwrap();
    let mut mu_bytes = [0u8; 32];
    mu_bytes.copy_from_slice(&proof_bytes[32..64]);
    let mu = axiom_scalar_from_be_bytes(&mu_bytes);

    let mut r_bytes = [0u8; 33];
    r_bytes[0] = 0x02;
    r_bytes[1..].copy_from_slice(&proof_bytes[..32]);
    let honest_r_projective = projective_from_compressed(&r_bytes);
    let corrupted_r_projective = honest_r_projective + ProjectivePoint::GENERATOR;

    [
        ("round1-honest-pok", honest_r_projective, true),
        ("round1-corrupted-pok", corrupted_r_projective, false),
    ]
    .into_iter()
    .map(|(name, transcript_r_projective, expect_match)| {
        let transcript_r_bytes = compressed_from_projective(transcript_r_projective);
        let challenge = round1_challenge(identifier, &phi0_bytes, &transcript_r_bytes);
        let witness = DkgRound1PokDigestFaultWitness {
            identifier: u64::from(participant_identifier),
            mu,
            challenge,
            phi0,
            transcript_r: axiom_point_from_projective(transcript_r_projective),
        };
        Round1Case {
            name: name.to_string(),
            witness,
            expect_residual_matches_transcript: expect_match,
        }
    })
    .collect()
}

fn round1_challenge(identifier: Identifier, phi0_bytes: &[u8; 33], r_bytes: &[u8; 33]) -> Fq {
    let mut challenge_preimage = Vec::new();
    challenge_preimage.extend_from_slice(&identifier.serialize());
    challenge_preimage.extend_from_slice(phi0_bytes);
    challenge_preimage.extend_from_slice(r_bytes);
    let challenge = frost::Secp256K1Sha256TR::HDKG(&challenge_preimage).unwrap();
    let challenge_bytes: [u8; 32] = challenge.to_bytes().into();
    axiom_scalar_from_be_bytes(&challenge_bytes)
}

fn round2_fixtures() -> Vec<Round2Case> {
    let mut rng = ChaCha20Rng::seed_from_u64(0x524f_554e_4432);
    let ids: Vec<Identifier> = (1..=3u16)
        .map(|id| Identifier::try_from(id).unwrap())
        .collect();

    let mut round1_secrets = BTreeMap::new();
    let mut round1_packages = BTreeMap::new();
    for &id in &ids {
        let (secret, package) = participant::dkg_part1(id, 3, 2, &mut rng).unwrap();
        round1_secrets.insert(id, secret);
        round1_packages.insert(id, package);
    }

    let mut round2_packages_per_sender = BTreeMap::new();
    for &id in &ids {
        let others: BTreeMap<_, _> = round1_packages
            .iter()
            .filter(|&(&peer, _)| peer != id)
            .map(|(&peer, package)| (peer, package.clone()))
            .collect();
        let secret = round1_secrets.remove(&id).unwrap();
        let (_secret2, packages2) = participant::dkg_part2(secret, &others).unwrap();
        round2_packages_per_sender.insert(id, packages2);
    }

    let sender = ids[0];
    let recipient = ids[1];
    let participant_index = 2u64;
    let commitments = round1_packages[&sender]
        .commitment()
        .serialize()
        .unwrap()
        .into_iter()
        .map(|bytes| {
            let bytes: [u8; 33] = bytes.as_slice().try_into().unwrap();
            axiom_point_from_compressed(&bytes)
        })
        .collect::<Vec<_>>();

    let share_bytes = round2_packages_per_sender[&sender][&recipient]
        .signing_share()
        .serialize();
    let share_bytes: [u8; 32] = share_bytes.as_slice().try_into().unwrap();
    let honest_share = axiom_scalar_from_be_bytes(&share_bytes);
    let corrupted_share = {
        let scalar = Scalar::from_repr(share_bytes.into()).unwrap() + Scalar::ONE;
        let bytes: [u8; 32] = scalar.to_bytes().into();
        axiom_scalar_from_be_bytes(&bytes)
    };

    [
        ("round2-honest-share", honest_share, true),
        ("round2-corrupted-share", corrupted_share, false),
    ]
    .into_iter()
    .map(|(name, share, expect_identity)| Round2Case {
        name: name.to_string(),
        witness: DkgRound2ShareFaultWitness {
            share,
            participant_index,
            commitments: commitments.clone(),
        },
        expect_identity_residual: expect_identity,
    })
    .collect()
}

fn projective_from_compressed(bytes: &[u8; 33]) -> ProjectivePoint {
    let encoded = EncodedPoint::from_bytes(bytes).unwrap();
    let affine = Option::<AffinePoint>::from(AffinePoint::from_encoded_point(&encoded)).unwrap();
    ProjectivePoint::from(affine)
}

fn compressed_from_projective(point: ProjectivePoint) -> [u8; 33] {
    let encoded = point.to_affine().to_encoded_point(true);
    encoded.as_bytes().try_into().unwrap()
}
