use std::{
    collections::BTreeMap,
    env, fs,
    path::{Path, PathBuf},
    process::{Command, Stdio},
    time::{Duration, Instant},
};

use bitcoin::secp256k1::{Keypair, Secp256k1, SecretKey};
use frost::Identifier;
use frost_secp256k1_tr as frost;
use halo2_base::halo2_proofs::{
    halo2curves::{
        bls12_381::{Bls12, Fr as BlsFr, G1Affine},
        ff::PrimeField,
        secp256k1::Fq,
    },
    plonk::{Circuit, ProvingKey, create_proof, keygen_pk, keygen_vk, verify_proof},
    poly::{
        commitment::ParamsProver,
        kzg::{
            commitment::{KZGCommitmentScheme, ParamsKZG},
            multiopen::{ProverSHPLONK, VerifierSHPLONK},
            strategy::SingleStrategy,
        },
    },
    transcript::{Challenge255, TranscriptReadBuffer, TranscriptWriterBuffer},
};
use heimdall::cardano::apply_ban::{ApplyBanRequest, FaultProofUtxo, build_apply_ban_tx};
use heimdall::cardano::ban_list::{
    BAN_ROOT_KEY, BanElement, BanElementData, BanPolicyParams, fault_token_name,
};
use heimdall::cardano::bf_http::{BfAmount, BfUtxo};
use heimdall::cardano::blueprint::{self, FaultVerifierKind, ParameterizedScript};
use heimdall::cardano::fault_proof::{
    EquivocationEvidence as OnchainEquivocationEvidence, FaultProofEvidence, FaultProofMintRequest,
    FaultProofRefScript, Round1InvalidPayloadEvidence, Round2InvalidPayloadEvidence,
    build_fault_proof_mint_tx,
};
use heimdall::cardano::hash::blake2b_256;
use heimdall::cardano::local_eval::{DEFAULT_TX_EX_UNIT_LIMITS, ExUnits, evaluate_tx_phase2};
use heimdall::cardano::publish::WalletUtxo;
use heimdall::cardano::registry::{ElementData, RegistrationNodeData, RegistryElement};
use heimdall::cardano::wallet::{derive_payment_key, wallet_address};
use heimdall::circuits::cardano_transcript::{CardanoBlake2bRead, CardanoBlake2bWrite};
use heimdall::circuits::fault_evidence;
use heimdall::http::{auth, canonical, frost_bridge};
use pallas_codec::minicbor;
use pallas_primitives::conway::Tx;
use plutus_halo2_verifier_gen::plutus_gen::{
    AxiomShplonkAikenOutputPaths, generate_axiom_shplonk_aiken_from_vk_and_instances,
};
use rand::{SeedableRng, rngs::StdRng};
use rand_chacha::ChaCha20Rng;
use serde_json::Value;
use uplc::tx::SlotConfig;
use whisky_common::{Asset, Network as WhiskyNetwork, UTxO, UtxoInput, UtxoOutput};
use whisky_pallas::wrapper::transaction_body::{ScriptRef, ScriptRefKind};

use heimdall::circuits::dkg_fault::{
    AxiomDkgCircuitParams, CircuitStats, DkgRound1PokDigestFaultWitness,
    DkgRound2ShareFaultWitness, axiom_scalar_from_be_bytes, be_bytes_from_fq,
    build_round1_digest_fault_keygen_circuit, build_round1_digest_fault_prover_circuit,
    build_round2_digest_fault_keygen_circuit, build_round2_digest_fault_prover_circuit,
    is_identity, round1_digest_fault_public_inputs, round1_digest_residual, round1_hdk_challenge,
    round1_message_digest, round2_digest_fault_public_inputs, round2_message_digest,
    round2_residual,
};
use heimdall::frost::participant;

const ROUND2_T: usize = 2;
const ROUND2_INDEX_BITS: usize = 16;
const BENCH_POOL_ID: [u8; 28] = [0x51; 28];
const BENCH_EPOCH: u64 = 7;
const BENCH_THRESHOLD: u64 = 51;
const BENCH_ATTEMPT: u64 = 0;
const BENCH_BASE_BAN_DURATION_MS: i64 = 86_400_000;
const BENCH_MAX_FAULTS_BEFORE_PERMANENT: i64 = 3;
const BENCH_MAX_VALIDITY_WINDOW_MS: i64 = 600_000;
const TARGET_ROOT: &str = "target/dkg_fault_onchain";
const GENERATE_ONLY_ENV: &str = "DKG_FAULT_ONCHAIN_GENERATE_ONLY";
const MAX_TX_SIZE_BYTES_ENV: &str = "DKG_FAULT_MAX_TX_SIZE_BYTES";
const DEFAULT_MAX_TX_SIZE_BYTES: usize = 16_384;
const TEST_MNEMONIC: &str =
    "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";
const AIKEN_TOML: &str = r#"name = "heimdall/dkg_fault_onchain_benchmark"
version = "0.0.0"
compiler = "v1.1.23"
plutus = "v3"
license = "Apache-2.0"
description = "Generated DKG fault proof on-chain benchmark project"

[repository]
user = "heimdall"
project = "dkg_fault_onchain_benchmark"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2.2.0"
source = "github"

[config.default]
network_id = 1
"#;
const AIKEN_LOCK: &str = r#"# This file was generated by Aiken
# You typically do not need to edit this file

[[requirements]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[[requirements]]
name = "aiken-lang/fuzz"
version = "v2.2.0"
source = "github"

[[packages]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
requirements = []
source = "github"

[[packages]]
name = "aiken-lang/fuzz"
version = "v2.2.0"
requirements = []
source = "github"

[etags]
"#;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum RunMode {
    Benchmark,
    GenerateOnly,
}

fn main() {
    let mode = run_mode();
    let limits = tx_ex_unit_limits();
    let max_tx_size_bytes = max_tx_size_bytes();
    println!(
        "backend: Axiom halo2-axiom, BLS12-381 KZG, SHPLONK, Cardano-friendly Blake2b transcript"
    );
    println!("standalone_onchain_benchmark: generated Aiken Plutus V3 minting policy");
    println!(
        "full_tx_benchmark: Bifrost fault verifier policy in a signed tx with reference script"
    );
    println!("mode: {mode:?}");
    println!("max_tx_ex_units_mem: {}", limits.mem);
    println!("max_tx_ex_units_cpu: {}", limits.cpu);
    println!("max_tx_size_bytes: {max_tx_size_bytes}");
    if mode == RunMode::Benchmark {
        println!("bifrost_plutus_json_url: {}", bifrost_plutus_json_url());
    }

    let reports = match env::var("DKG_FAULT_ONCHAIN_ROUND").as_deref() {
        Ok("round1") => run_round1_onchain(AxiomDkgCircuitParams::round1_digest_fault(), mode),
        Ok("round2") => run_round2_onchain(AxiomDkgCircuitParams::round2_digest_fault(), mode),
        Ok("equivocation") => run_equivocation_onchain(mode),
        Ok("all") | Err(_) => {
            let mut reports =
                run_round1_onchain(AxiomDkgCircuitParams::round1_digest_fault(), mode);
            reports.extend(run_round2_onchain(
                AxiomDkgCircuitParams::round2_digest_fault(),
                mode,
            ));
            reports.extend(run_equivocation_onchain(mode));
            reports
        }
        Ok(other) => {
            panic!(
                "DKG_FAULT_ONCHAIN_ROUND must be round1, round2, equivocation, or all; got {other}"
            )
        }
    }
    .into_iter()
    .collect::<Vec<_>>();

    if mode == RunMode::Benchmark {
        assert_all_within_tx_budget(&reports, limits);
    }
}

fn run_mode() -> RunMode {
    let generate_only = env::var(GENERATE_ONLY_ENV)
        .map(|value| matches!(value.as_str(), "1" | "true" | "TRUE" | "yes" | "YES"))
        .unwrap_or(false);
    if generate_only {
        RunMode::GenerateOnly
    } else {
        RunMode::Benchmark
    }
}

fn run_round1_onchain(params: AxiomDkgCircuitParams, mode: RunMode) -> Vec<BudgetReport> {
    let cases = round1_fixtures();
    let corrupted = cases
        .iter()
        .find(|case| !case.expect_residual_matches_transcript)
        .expect("round 1 corrupted fixture")
        .clone();
    let honest = cases
        .iter()
        .find(|case| case.expect_residual_matches_transcript)
        .expect("round 1 honest fixture")
        .clone();

    let (keygen_builder, stats) =
        build_round1_digest_fault_keygen_circuit(params, &corrupted.witness);
    let setup = setup(params);
    let (pk, break_points, keygen_times) = keygen(&setup, keygen_builder);

    println!();
    println!("== round1-onchain-pok-digest-fault ==");
    print_circuit_config(params);
    print_stats(&stats, params);
    print_keygen_times(&keygen_times);

    let corrupted_artifact = prove_round1_digest_fault_case(
        &setup,
        &pk,
        stats.config_params.clone(),
        break_points,
        params,
        &corrupted,
    );
    let honest_digest = round1_message_digest(params, &honest.witness);
    let honest_artifact = corrupted_artifact.with_digest("round1-honest-digest", honest_digest);
    print_digest_proof_artifact(&corrupted_artifact);

    let project_dir =
        generate_digest_project("round1", &setup, &pk, &corrupted_artifact, &honest_artifact);
    print_generated_project(&project_dir);
    if mode == RunMode::GenerateOnly {
        return Vec::new();
    }

    let mut reports = Vec::new();
    let aiken_start = Instant::now();
    let aiken_output = run_aiken_check(&project_dir);
    let aiken_time = aiken_start.elapsed();
    let budget = parse_aiken_budget(&aiken_output, "round1_corrupted_mint_benchmark")
        .expect("round 1 Aiken benchmark ExUnits should be present");
    print_onchain_budget("round1_corrupted_mint_benchmark", budget, aiken_time);
    reports.push(BudgetReport {
        name: "round1_corrupted_mint_benchmark",
        budget,
    });
    reports.extend(run_round1_full_tx_benchmark(
        &corrupted,
        &corrupted_artifact,
        tx_ex_unit_limits(),
    ));
    reports
}

fn run_round2_onchain(params: AxiomDkgCircuitParams, mode: RunMode) -> Vec<BudgetReport> {
    let cases = round2_fixtures();
    let corrupted = cases
        .iter()
        .find(|case| !case.expect_identity_residual)
        .expect("round 2 corrupted fixture")
        .clone();
    let honest = cases
        .iter()
        .find(|case| case.expect_identity_residual)
        .expect("round 2 honest fixture")
        .clone();

    let (keygen_builder, stats) = build_round2_digest_fault_keygen_circuit::<
        ROUND2_T,
        ROUND2_INDEX_BITS,
    >(params, &corrupted.witness);
    let setup = setup(params);
    let (pk, break_points, keygen_times) = keygen(&setup, keygen_builder);

    println!();
    println!("== round2-onchain-share-digest-fault ==");
    print_circuit_config(params);
    print_stats(&stats, params);
    print_keygen_times(&keygen_times);

    let corrupted_artifact = prove_round2_digest_fault_case(
        &setup,
        &pk,
        stats.config_params.clone(),
        break_points,
        params,
        &corrupted,
    );
    let honest_digest =
        round2_message_digest::<ROUND2_T, ROUND2_INDEX_BITS>(params, &honest.witness);
    let honest_artifact = corrupted_artifact.with_digest("round2-honest-digest", honest_digest);
    print_digest_proof_artifact(&corrupted_artifact);

    let project_dir =
        generate_digest_project("round2", &setup, &pk, &corrupted_artifact, &honest_artifact);
    print_generated_project(&project_dir);
    if mode == RunMode::GenerateOnly {
        return Vec::new();
    }

    let mut reports = Vec::new();
    let aiken_start = Instant::now();
    let aiken_output = run_aiken_check(&project_dir);
    let aiken_time = aiken_start.elapsed();
    let budget = parse_aiken_budget(&aiken_output, "round2_corrupted_mint_benchmark")
        .expect("round 2 Aiken benchmark ExUnits should be present");
    print_onchain_budget("round2_corrupted_mint_benchmark", budget, aiken_time);
    reports.push(BudgetReport {
        name: "round2_corrupted_mint_benchmark",
        budget,
    });
    reports.extend(run_round2_full_tx_benchmark(
        &corrupted,
        &corrupted_artifact,
        tx_ex_unit_limits(),
    ));
    reports
}

fn run_equivocation_onchain(mode: RunMode) -> Vec<BudgetReport> {
    println!();
    println!("== equivocation-onchain-fault ==");
    println!("zk_circuit: none");
    if mode == RunMode::GenerateOnly {
        return Vec::new();
    }

    let case = equivocation_fixture();
    let evidence_hash = case.evidence.evidence_hash();
    println!("case: {}", case.name);
    println!("  evidence_hash: {}", hex::encode(evidence_hash));
    run_equivocation_full_tx_benchmark(&case, tx_ex_unit_limits())
}

fn run_round1_full_tx_benchmark(
    case: &Round1Case,
    artifact: &DigestProofArtifact,
    limits: ExUnits,
) -> Vec<BudgetReport> {
    let scripts = bifrost_fault_scripts(FaultVerifierKind::Round1);
    let canonical_round1_bytes = case.evidence.canonical_bytes().unwrap();
    let evidence_hash = case.evidence.evidence_hash().unwrap();
    assert_eq!(evidence_hash, bls_scalar_bytes(artifact.digest));
    let public_inputs = public_input_bytes(evidence_hash, case.evidence.accused_pool_id);

    let evidence = FaultProofEvidence::Round1InvalidPayload(Round1InvalidPayloadEvidence {
        accused_pool_id: &case.evidence.accused_pool_id,
        canonical_round1_bytes: &canonical_round1_bytes,
        payload_signature: &case.evidence.payload_signature,
        halo2_proof: &artifact.proof,
        halo2_public_inputs: &public_inputs,
    });
    run_full_tx_benchmark(
        "round1_fault_mint_full_tx_phase2",
        "round1_apply_ban_full_tx_phase2",
        &scripts,
        case.evidence.bifrost_id_pk,
        evidence,
        limits,
    )
}

fn run_round2_full_tx_benchmark(
    case: &Round2Case,
    artifact: &DigestProofArtifact,
    limits: ExUnits,
) -> Vec<BudgetReport> {
    let scripts = bifrost_fault_scripts(FaultVerifierKind::Round2);
    let evidence_hash = case.evidence.evidence_hash::<ROUND2_T>().unwrap();
    assert_eq!(evidence_hash, bls_scalar_bytes(artifact.digest));
    let public_inputs = public_input_bytes(evidence_hash, case.evidence.accused_pool_id);

    let evidence = FaultProofEvidence::Round2InvalidPayload(Round2InvalidPayloadEvidence {
        accused_pool_id: &case.evidence.accused_pool_id,
        canonical_round1_bytes: &case.evidence.canonical_round1_bytes,
        round1_signature: &case.evidence.round1_signature,
        canonical_round2_bytes: &case.evidence.round2_canonical_bytes,
        round2_signature: &case.evidence.round2_signature,
        round2_entry_index: case.evidence.round2_entry_index,
        pad: &case.evidence.pad,
        opened_share: &case.evidence.share,
        halo2_proof: &artifact.proof,
        halo2_public_inputs: &public_inputs,
    });
    run_full_tx_benchmark(
        "round2_fault_mint_full_tx_phase2",
        "round2_apply_ban_full_tx_phase2",
        &scripts,
        case.evidence.bifrost_id_pk,
        evidence,
        limits,
    )
}

fn run_equivocation_full_tx_benchmark(
    case: &EquivocationCase,
    limits: ExUnits,
) -> Vec<BudgetReport> {
    let scripts = bifrost_fault_scripts(FaultVerifierKind::Equivocation);
    let evidence_hash = case.evidence.evidence_hash();
    let evidence = FaultProofEvidence::Equivocation(OnchainEquivocationEvidence {
        accused_pool_id: &case.evidence.accused_pool_id,
        payload_a: &case.evidence.payload_a,
        signature_a: &case.evidence.signature_a,
        payload_b: &case.evidence.payload_b,
        signature_b: &case.evidence.signature_b,
        evidence_hash: &evidence_hash,
    });
    run_full_tx_benchmark(
        "equivocation_fault_mint_full_tx_phase2",
        "equivocation_apply_ban_full_tx_phase2",
        &scripts,
        case.evidence.bifrost_id_pk,
        evidence,
        limits,
    )
}

fn run_full_tx_benchmark(
    mint_name: &'static str,
    apply_ban_name: &'static str,
    scripts: &BifrostFaultScripts,
    accused_bifrost_id_pk: [u8; 32],
    evidence: FaultProofEvidence<'_>,
    limits: ExUnits,
) -> Vec<BudgetReport> {
    let key = derive_payment_key(TEST_MNEMONIC).unwrap();
    let wallet_address = wallet_address(&key);
    let wallet_utxos = bench_wallet_utxos();
    let accused_pool_id: [u8; 28] = evidence
        .accused_pool_id()
        .try_into()
        .expect("benchmark pool id is 28 bytes");
    let evidence_hash = evidence.evidence_hash().expect("benchmark evidence hash");
    let registration_tx_hash = tx_hash_hex(0xC1);
    let registration_output_index = 0;
    let registration_utxo = registration_node_utxo(
        &scripts.registry,
        &registration_tx_hash,
        registration_output_index,
        &accused_pool_id,
        &accused_bifrost_id_pk,
    );
    let fault_ref_tx_hash = tx_hash_hex(0xC2);
    let fault_ref_output_index = 0;
    let script_ref_utxo = fault_verifier_script_ref_utxo(
        &scripts.fault_verifier,
        &fault_ref_tx_hash,
        fault_ref_output_index,
        &wallet_address,
    );
    let built = build_fault_proof_mint_tx(&FaultProofMintRequest {
        fault_verifier_script: &scripts.fault_verifier,
        fault_verifier_ref_script: Some(FaultProofRefScript {
            tx_hash: &fault_ref_tx_hash,
            output_index: fault_ref_output_index,
            script_size: scripts.fault_verifier.cbor.len(),
        }),
        evidence,
        registration_ref: (&registration_tx_hash, registration_output_index),
        wallet_address: &wallet_address,
        wallet_utxos: &wallet_utxos,
        key: &key,
        cost_models: None,
    })
    .expect("full fault-proof mint tx builds");
    let shape = tx_shape(&built.signed_tx_hex);
    let tx_size_bytes = built.signed_tx_hex.len() / 2;
    let max_tx_size_bytes = max_tx_size_bytes();
    assert!(
        tx_size_bytes <= max_tx_size_bytes,
        "{mint_name} tx size exceeds limit: size={tx_size_bytes} max={max_tx_size_bytes}"
    );
    let resolved_utxos = resolved_benchmark_utxos(
        &wallet_utxos,
        &wallet_address,
        &[registration_utxo.clone(), script_ref_utxo.clone()],
    );

    let eval_start = Instant::now();
    let report = evaluate_tx_phase2(
        &built.signed_tx_hex,
        &resolved_utxos,
        &WhiskyNetwork::Preprod,
        &SlotConfig::default(),
        None,
    )
    .expect("full fault-proof mint tx phase-2 evaluation succeeds within limits");
    let eval_time = eval_start.elapsed();
    assert_eq!(
        report.actions.len(),
        1,
        "fault-proof tx should run one Plutus script"
    );

    print_full_tx_budget(
        mint_name,
        tx_size_bytes,
        max_tx_size_bytes,
        &report,
        shape,
        &scripts.blueprint_source,
        eval_time,
    );
    assert_within_tx_budget(mint_name, report.total, limits);

    let mint_report = BudgetReport {
        name: mint_name,
        budget: report.total,
    };
    let apply_ban_report = run_apply_ban_full_tx_benchmark(
        apply_ban_name,
        scripts,
        &key,
        &wallet_address,
        &wallet_utxos,
        &registration_tx_hash,
        registration_output_index,
        registration_utxo,
        fault_ref_tx_hash,
        fault_ref_output_index,
        script_ref_utxo,
        accused_pool_id,
        evidence_hash,
        &built,
        limits,
    );
    vec![mint_report, apply_ban_report]
}

struct BifrostFaultScripts {
    registry: ParameterizedScript,
    fault_verifier: ParameterizedScript,
    spo_bans: ParameterizedScript,
    ban_params: BanPolicyParams,
    blueprint_source: String,
}

fn bifrost_fault_scripts(kind: FaultVerifierKind) -> BifrostFaultScripts {
    let blueprint_json = fetch_bifrost_plutus_json();
    let registry = blueprint::spos_registry_script(&blueprint_json, &[0xC0; 32], 0)
        .expect("parameterize benchmark spos_registry");
    let round1_fault = blueprint::fault_verifier_script(
        &blueprint_json,
        FaultVerifierKind::Round1,
        &registry.hash,
    )
    .expect("parameterize benchmark round 1 fault verifier");
    let round2_fault = blueprint::fault_verifier_script(
        &blueprint_json,
        FaultVerifierKind::Round2,
        &registry.hash,
    )
    .expect("parameterize benchmark round 2 fault verifier");
    let equivocation_fault = blueprint::fault_verifier_script(
        &blueprint_json,
        FaultVerifierKind::Equivocation,
        &registry.hash,
    )
    .expect("parameterize benchmark equivocation fault verifier");
    let policy_ids = vec![
        round1_fault.hash,
        round2_fault.hash,
        equivocation_fault.hash,
    ];
    let ban_params = BanPolicyParams {
        fault_proof_policies: policy_ids.clone(),
        base_ban_duration_ms: BENCH_BASE_BAN_DURATION_MS,
        max_faults_before_permanent: BENCH_MAX_FAULTS_BEFORE_PERMANENT,
        max_validity_window_ms: BENCH_MAX_VALIDITY_WINDOW_MS,
    };
    let spo_bans = blueprint::spo_bans_script(
        &blueprint_json,
        &registry.hash,
        &policy_ids,
        ban_params.base_ban_duration_ms,
        ban_params.max_faults_before_permanent,
        ban_params.max_validity_window_ms,
        &[0xD0; 32],
        0,
    )
    .expect("parameterize benchmark spo_bans");
    let fault_verifier = match kind {
        FaultVerifierKind::Round1 => round1_fault,
        FaultVerifierKind::Round2 => round2_fault,
        FaultVerifierKind::Equivocation => equivocation_fault,
    };
    BifrostFaultScripts {
        registry,
        fault_verifier,
        spo_bans,
        ban_params,
        blueprint_source: bifrost_plutus_json_url().to_string(),
    }
}

fn bifrost_plutus_json_url() -> &'static str {
    "https://raw.githubusercontent.com/FluidTokens/ft-bifrost-bridge/4785169751c297618966fcd085b8d2612df7cb27/onchain/plutus.json"
}

fn fetch_bifrost_plutus_json() -> String {
    let url = bifrost_plutus_json_url();
    let runtime = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .expect("create benchmark HTTP runtime");
    runtime.block_on(async {
        let response = reqwest::get(url)
            .await
            .unwrap_or_else(|err| panic!("fetch Bifrost plutus.json from {url}: {err}"));
        let status = response.status();
        assert!(
            status.is_success(),
            "fetch Bifrost plutus.json from {url}: HTTP {status}"
        );
        response
            .text()
            .await
            .unwrap_or_else(|err| panic!("read Bifrost plutus.json from {url}: {err}"))
    })
}

#[allow(clippy::too_many_arguments)]
fn run_apply_ban_full_tx_benchmark(
    name: &'static str,
    scripts: &BifrostFaultScripts,
    key: &pallas_wallet::PrivateKey,
    wallet_address: &str,
    wallet_utxos: &[WalletUtxo],
    registration_tx_hash: &str,
    registration_output_index: u32,
    registration_utxo: UTxO,
    fault_ref_tx_hash: String,
    fault_ref_output_index: u32,
    fault_ref_utxo: UTxO,
    accused_pool_id: [u8; 28],
    evidence_hash: [u8; 32],
    mint: &heimdall::cardano::fault_proof::FaultProofMintTx,
    limits: ExUnits,
) -> BudgetReport {
    assert_eq!(
        mint.token_name,
        fault_token_name(&accused_pool_id, &evidence_hash)
    );
    let ban_root_tx_hash = tx_hash_hex(0xC4);
    let ban_root_output_index = 0;
    let ban_root_bf = ban_root_bfutxo(&scripts.spo_bans, &ban_root_tx_hash, ban_root_output_index);
    let ban_root_utxo = ban_element_resolved_utxo(&scripts.spo_bans, &ban_root_bf);
    let spo_bans_ref_tx_hash = tx_hash_hex(0xC5);
    let spo_bans_ref_output_index = 0;
    let spo_bans_ref_utxo = script_ref_utxo(
        &scripts.spo_bans,
        &spo_bans_ref_tx_hash,
        spo_bans_ref_output_index,
        wallet_address,
    );
    let fault_utxo = FaultProofUtxo {
        tx_hash: tx_hash_hex(0xC3),
        output_index: 0,
        lovelace: mint.lovelace,
    };
    let fault_resolved_utxo = fault_proof_resolved_utxo(
        &mint.policy_id_hex,
        &mint.token_name,
        &fault_utxo,
        wallet_address,
    );
    let (invalid_before, invalid_hereafter, start_time_ms) = apply_ban_benchmark_window();
    let built = build_apply_ban_tx(&ApplyBanRequest {
        spo_bans_script: &scripts.spo_bans,
        fault_verifier_script: &scripts.fault_verifier,
        fault_verifier_ref: Some((fault_ref_tx_hash, fault_ref_output_index)),
        ban_params: &scripts.ban_params,
        accused_pool_id,
        evidence_hash,
        ban_utxos: &[ban_root_bf],
        fault_utxo: &fault_utxo,
        registration_ref: (registration_tx_hash.to_string(), registration_output_index),
        spo_bans_ref: (spo_bans_ref_tx_hash, spo_bans_ref_output_index),
        mainnet: false,
        start_time_ms,
        invalid_before,
        invalid_hereafter,
        wallet_address,
        wallet_utxos,
        key,
        cost_models: None,
    })
    .expect("full apply-ban tx builds");

    assert!(
        built.first_ban,
        "benchmark uses the first-ban transaction shape"
    );
    let shape = tx_shape(&built.signed_tx_hex);
    let tx_size_bytes = built.signed_tx_hex.len() / 2;
    let max_tx_size_bytes = max_tx_size_bytes();
    assert!(
        tx_size_bytes <= max_tx_size_bytes,
        "{name} tx size exceeds limit: size={tx_size_bytes} max={max_tx_size_bytes}"
    );
    let resolved_utxos = resolved_benchmark_utxos(
        wallet_utxos,
        wallet_address,
        &[
            registration_utxo,
            fault_ref_utxo,
            ban_root_utxo,
            spo_bans_ref_utxo,
            fault_resolved_utxo,
        ],
    );
    let eval_start = Instant::now();
    let report = evaluate_tx_phase2(
        &built.signed_tx_hex,
        &resolved_utxos,
        &WhiskyNetwork::Preprod,
        &SlotConfig::default(),
        None,
    )
    .expect("full apply-ban tx phase-2 evaluation succeeds");
    let eval_time = eval_start.elapsed();
    assert_eq!(
        report.actions.len(),
        4,
        "first-ban tx should run four Plutus scripts"
    );

    print_full_tx_budget(
        name,
        tx_size_bytes,
        max_tx_size_bytes,
        &report,
        shape,
        &scripts.blueprint_source,
        eval_time,
    );
    println!("apply_ban_first_ban: {}", built.first_ban);
    println!("apply_ban_ban_counter: {}", built.ban_node.ban_counter);
    println!(
        "apply_ban_ban_until_time_ms: {}",
        built.ban_node.ban_until_time
    );
    assert_within_tx_budget(name, report.total, limits);
    BudgetReport {
        name,
        budget: report.total,
    }
}

fn apply_ban_benchmark_window() -> (u64, u64, i64) {
    let slot_config = SlotConfig::default();
    let invalid_before = slot_config.zero_slot;
    let invalid_hereafter = invalid_before + 1;
    let start_time_ms =
        i64::try_from(slot_config.zero_time + u64::from(slot_config.slot_length) - 1)
            .expect("default slot time fits i64");
    (invalid_before, invalid_hereafter, start_time_ms)
}

fn ban_root_bfutxo(spo_bans: &ParameterizedScript, tx_hash: &str, output_index: u32) -> BfUtxo {
    let root = BanElement {
        data: BanElementData::Root,
        link: None,
    };
    BfUtxo {
        tx_hash: tx_hash.to_string(),
        output_index,
        amount: vec![
            BfAmount {
                unit: "lovelace".to_string(),
                quantity: "2000000".to_string(),
            },
            BfAmount {
                unit: format!("{}{}", spo_bans.hash_hex(), hex::encode(BAN_ROOT_KEY)),
                quantity: "1".to_string(),
            },
        ],
        inline_datum: Some(hex::encode(root.to_cbor())),
        reference_script_hash: None,
    }
}

fn ban_element_resolved_utxo(spo_bans: &ParameterizedScript, utxo: &BfUtxo) -> UTxO {
    UTxO {
        input: UtxoInput {
            tx_hash: utxo.tx_hash.clone(),
            output_index: utxo.output_index,
        },
        output: UtxoOutput {
            address: spo_bans.enterprise_address(pallas_addresses::Network::Testnet),
            amount: utxo
                .amount
                .iter()
                .map(|asset| Asset::new_from_str(&asset.unit, &asset.quantity))
                .collect(),
            data_hash: None,
            plutus_data: utxo.inline_datum.clone(),
            script_ref: None,
            script_hash: Some(spo_bans.hash_hex()),
        },
    }
}

fn fault_proof_resolved_utxo(
    policy_id_hex: &str,
    token_name: &[u8; 32],
    fault_utxo: &FaultProofUtxo,
    address: &str,
) -> UTxO {
    UTxO {
        input: UtxoInput {
            tx_hash: fault_utxo.tx_hash.clone(),
            output_index: fault_utxo.output_index,
        },
        output: UtxoOutput {
            address: address.to_string(),
            amount: vec![
                Asset::new_from_str("lovelace", &fault_utxo.lovelace.to_string()),
                Asset::new_from_str(&format!("{policy_id_hex}{}", hex::encode(token_name)), "1"),
            ],
            data_hash: None,
            plutus_data: None,
            script_ref: None,
            script_hash: None,
        },
    }
}

fn fault_verifier_script_ref_utxo(
    fault_verifier: &ParameterizedScript,
    tx_hash: &str,
    output_index: u32,
    address: &str,
) -> UTxO {
    script_ref_utxo(fault_verifier, tx_hash, output_index, address)
}

fn script_ref_utxo(
    script: &ParameterizedScript,
    tx_hash: &str,
    output_index: u32,
    address: &str,
) -> UTxO {
    let script_ref = ScriptRef::new(ScriptRefKind::PlutusV3Script {
        plutus_v3_script_hex: script.cbor_hex(),
    })
    .expect("script ref")
    .encode()
    .expect("script ref CBOR");
    UTxO {
        input: UtxoInput {
            tx_hash: tx_hash.to_string(),
            output_index,
        },
        output: UtxoOutput {
            address: address.to_string(),
            amount: vec![Asset::new_from_str("lovelace", "5000000")],
            data_hash: None,
            plutus_data: None,
            script_ref: Some(script_ref),
            script_hash: None,
        },
    }
}

fn bench_wallet_utxos() -> Vec<WalletUtxo> {
    vec![
        WalletUtxo {
            tx_hash: tx_hash_hex(0xA1),
            output_index: 0,
            lovelace: 50_000_000,
            pure_ada: true,
        },
        WalletUtxo {
            tx_hash: tx_hash_hex(0xA2),
            output_index: 1,
            lovelace: 6_000_000,
            pure_ada: true,
        },
    ]
}

fn resolved_benchmark_utxos(
    wallet_utxos: &[WalletUtxo],
    wallet_address: &str,
    extra_utxos: &[UTxO],
) -> Vec<UTxO> {
    let mut resolved = wallet_utxos
        .iter()
        .map(|utxo| wallet_resolved_utxo(utxo, wallet_address))
        .collect::<Vec<_>>();
    resolved.extend_from_slice(extra_utxos);
    resolved
}

fn wallet_resolved_utxo(utxo: &WalletUtxo, address: &str) -> UTxO {
    UTxO {
        input: UtxoInput {
            tx_hash: utxo.tx_hash.clone(),
            output_index: utxo.output_index,
        },
        output: UtxoOutput {
            address: address.to_string(),
            amount: vec![Asset::new_from_str("lovelace", &utxo.lovelace.to_string())],
            data_hash: None,
            plutus_data: None,
            script_ref: None,
            script_hash: None,
        },
    }
}

fn registration_node_utxo(
    registry: &ParameterizedScript,
    tx_hash: &str,
    output_index: u32,
    pool_id: &[u8],
    bifrost_id_pk: &[u8; 32],
) -> UTxO {
    let datum = RegistryElement {
        data: ElementData::Node(RegistrationNodeData {
            bifrost_id_pk: bifrost_id_pk.to_vec(),
            bifrost_url: b"https://spo.example".to_vec(),
        }),
        link: None,
    };
    let registry_unit = format!("{}{}", registry.hash_hex(), hex::encode(pool_id));
    UTxO {
        input: UtxoInput {
            tx_hash: tx_hash.to_string(),
            output_index,
        },
        output: UtxoOutput {
            address: registry.enterprise_address(pallas_addresses::Network::Testnet),
            amount: vec![
                Asset::new_from_str("lovelace", "2000000"),
                Asset::new_from_str(&registry_unit, "1"),
            ],
            data_hash: None,
            plutus_data: Some(hex::encode(datum.to_cbor())),
            script_ref: None,
            script_hash: Some(registry.hash_hex()),
        },
    }
}

fn tx_hash_hex(byte: u8) -> String {
    hex::encode([byte; 32])
}

fn public_input_bytes(evidence_hash: [u8; 32], pool_id: [u8; 28]) -> Vec<Vec<u8>> {
    vec![evidence_hash.to_vec(), pool_id.to_vec()]
}

fn bls_scalar_bytes(scalar: BlsFr) -> [u8; 32] {
    let repr = scalar.to_repr();
    let mut out = [0u8; 32];
    out.copy_from_slice(repr.as_ref());
    out
}

fn tx_shape(tx_hex: &str) -> TxShape {
    let tx_bytes = hex::decode(tx_hex).expect("signed tx hex");
    let tx: Tx = minicbor::decode(&tx_bytes).expect("signed tx CBOR");
    TxShape {
        inputs: tx.transaction_body.inputs.len(),
        outputs: tx.transaction_body.outputs.len(),
        collateral_inputs: tx
            .transaction_body
            .collateral
            .as_ref()
            .map(|inputs| inputs.len())
            .unwrap_or(0),
        reference_inputs: tx
            .transaction_body
            .reference_inputs
            .as_ref()
            .map(|inputs| inputs.len())
            .unwrap_or(0),
    }
}

fn setup(params: AxiomDkgCircuitParams) -> ParamsKZG<Bls12> {
    ParamsKZG::<Bls12>::setup(params.degree, StdRng::seed_from_u64(2))
}

fn keygen(
    setup: &ParamsKZG<Bls12>,
    keygen_builder: halo2_base::gates::circuit::builder::RangeCircuitBuilder<BlsFr>,
) -> (ProvingKey<G1Affine>, Vec<Vec<usize>>, KeygenTimes) {
    let vk_start = Instant::now();
    let vk = keygen_vk(setup, &keygen_builder).expect("vkey generation should succeed");
    let vk_time = vk_start.elapsed();

    let pk_start = Instant::now();
    let pk = keygen_pk(setup, vk, &keygen_builder).expect("pkey generation should succeed");
    let pk_time = pk_start.elapsed();

    let break_points = keygen_builder.break_points();
    (pk, break_points, KeygenTimes { vk_time, pk_time })
}

fn prove_round1_digest_fault_case(
    setup: &ParamsKZG<Bls12>,
    pk: &ProvingKey<G1Affine>,
    config_params: halo2_base::gates::circuit::BaseCircuitParams,
    break_points: Vec<Vec<usize>>,
    params: AxiomDkgCircuitParams,
    case: &Round1Case,
) -> DigestProofArtifact {
    let witness_start = Instant::now();
    let (prover_builder, public_instances) = build_round1_digest_fault_prover_circuit(
        config_params,
        break_points,
        params,
        &case.witness,
    );
    let witness_time = witness_start.elapsed();

    let expected_digest = round1_message_digest(params, &case.witness);
    let expected_public_inputs = round1_digest_fault_public_inputs(params, &case.witness);
    assert_eq!(public_instances, expected_public_inputs);
    assert_eq!(case.witness.challenge, round1_hdk_challenge(&case.witness));
    let computed = round1_digest_residual(&case.witness);
    assert_eq!(
        computed == case.witness.transcript_r,
        case.expect_residual_matches_transcript
    );
    assert!(!case.expect_residual_matches_transcript);

    prove_digest_artifact(
        setup,
        pk,
        prover_builder,
        public_instances,
        expected_digest,
        case.witness.accused_pool_id,
        case.name.clone(),
        witness_time,
        "public inputs = [Poseidon(pool_id, message), pool_id], circuit derives HDKG and asserts D != R",
    )
}

fn prove_round2_digest_fault_case(
    setup: &ParamsKZG<Bls12>,
    pk: &ProvingKey<G1Affine>,
    config_params: halo2_base::gates::circuit::BaseCircuitParams,
    break_points: Vec<Vec<usize>>,
    params: AxiomDkgCircuitParams,
    case: &Round2Case,
) -> DigestProofArtifact {
    let witness_start = Instant::now();
    let (prover_builder, public_instances) = build_round2_digest_fault_prover_circuit::<
        ROUND2_T,
        ROUND2_INDEX_BITS,
    >(
        config_params, break_points, params, &case.witness
    );
    let witness_time = witness_start.elapsed();

    let expected_digest =
        round2_message_digest::<ROUND2_T, ROUND2_INDEX_BITS>(params, &case.witness);
    let expected_public_inputs =
        round2_digest_fault_public_inputs::<ROUND2_T, ROUND2_INDEX_BITS>(params, &case.witness);
    assert_eq!(public_instances, expected_public_inputs);
    let computed = round2_residual(&case.witness);
    assert!(!is_identity(&computed));

    prove_digest_artifact(
        setup,
        pk,
        prover_builder,
        public_instances,
        expected_digest,
        case.witness.accused_pool_id,
        case.name.clone(),
        witness_time,
        "public inputs = [Poseidon(pool_id, message), pool_id], circuit asserts D != identity",
    )
}

fn prove_digest_artifact<C>(
    setup: &ParamsKZG<Bls12>,
    pk: &ProvingKey<G1Affine>,
    circuit: C,
    public_instances: Vec<BlsFr>,
    digest: BlsFr,
    pool_id: [u8; 28],
    name: String,
    witness_time: Duration,
    host_check: &'static str,
) -> DigestProofArtifact
where
    C: Circuit<BlsFr>,
{
    let proof_start = Instant::now();
    let proof = gen_proof(setup, pk, circuit, &public_instances);
    let proof_time = proof_start.elapsed();

    let verify_start = Instant::now();
    verify(setup, pk, &proof, &public_instances);
    let verify_time = verify_start.elapsed();

    DigestProofArtifact {
        name,
        proof,
        public_instances,
        digest,
        pool_id,
        host_check,
        witness_time,
        proof_time,
        verify_time,
    }
}

fn gen_proof<C>(
    params: &ParamsKZG<Bls12>,
    pk: &ProvingKey<G1Affine>,
    circuit: C,
    public_instances: &[BlsFr],
) -> Vec<u8>
where
    C: Circuit<BlsFr>,
{
    let rng = StdRng::seed_from_u64(1);
    let instances: &[&[BlsFr]] = &[public_instances];
    let mut transcript = CardanoBlake2bWrite::<_, G1Affine>::init(vec![]);
    create_proof::<
        KZGCommitmentScheme<Bls12>,
        ProverSHPLONK<'_, Bls12>,
        Challenge255<_>,
        _,
        CardanoBlake2bWrite<Vec<u8>, G1Affine>,
        _,
    >(params, pk, &[circuit], &[instances], rng, &mut transcript)
    .expect("proof generation should succeed");
    transcript.finalize()
}

fn verify(
    params: &ParamsKZG<Bls12>,
    pk: &ProvingKey<G1Affine>,
    proof: &[u8],
    public_instances: &[BlsFr],
) {
    let verifier_params = params.verifier_params();
    let strategy = SingleStrategy::new(params);
    let instances: &[&[BlsFr]] = &[public_instances];
    let mut transcript = CardanoBlake2bRead::<_, G1Affine>::init(proof);
    verify_proof::<
        KZGCommitmentScheme<Bls12>,
        VerifierSHPLONK<'_, Bls12>,
        Challenge255<G1Affine>,
        CardanoBlake2bRead<&[u8], G1Affine>,
        SingleStrategy<'_, Bls12>,
    >(
        verifier_params,
        pk.get_vk(),
        strategy,
        &[instances],
        &mut transcript,
    )
    .expect("proof verification should succeed");
}

fn generate_digest_project(
    round_name: &str,
    setup: &ParamsKZG<Bls12>,
    pk: &ProvingKey<G1Affine>,
    corrupted: &DigestProofArtifact,
    honest: &DigestProofArtifact,
) -> PathBuf {
    let project_dir = prepare_project(round_name);
    let paths = generator_paths(&project_dir);

    let generator_start = Instant::now();
    generate_axiom_shplonk_aiken_from_vk_and_instances(
        setup,
        pk.get_vk(),
        &corrupted.proof,
        &[corrupted.public_instances.as_slice()],
        &paths,
    )
    .expect("Axiom SHPLONK verifier generation should succeed");
    println!(
        "{round_name}_generic_generator_time: {}",
        fmt_duration(generator_start.elapsed())
    );

    write_digest_policy(&project_dir, round_name, corrupted, honest);
    project_dir
}

fn print_generated_project(project_dir: &Path) {
    println!("generated_aiken_project: {}", project_dir.display());
    println!(
        "generated_plutus_blueprint_command: cd {} && aiken build",
        project_dir.display()
    );
}

fn prepare_project(round_name: &str) -> PathBuf {
    let project_dir = Path::new(TARGET_ROOT).join(round_name);
    if project_dir.exists() {
        fs::remove_dir_all(&project_dir).expect("remove stale generated Aiken project");
    }
    fs::create_dir_all(project_dir.join("lib")).expect("create generated Aiken lib dir");
    fs::create_dir_all(project_dir.join("validators")).expect("create validator output dir");
    fs::write(project_dir.join("aiken.toml"), AIKEN_TOML).expect("write generated Aiken manifest");
    fs::write(project_dir.join("aiken.lock"), AIKEN_LOCK).expect("write generated Aiken lock file");
    project_dir
}

fn generator_paths(project_dir: &Path) -> AxiomShplonkAikenOutputPaths {
    let support_dir = project_dir.join("lib");
    AxiomShplonkAikenOutputPaths {
        verifier_output: support_dir.join("proof_verifier.ak"),
        verifier_key_output: support_dir.join("verifier_key.ak"),
        support_dir,
    }
}

fn write_digest_policy(
    project_dir: &Path,
    round_name: &str,
    corrupted: &DigestProofArtifact,
    honest: &DigestProofArtifact,
) {
    let policy = digest_policy_source(round_name, corrupted, honest);
    fs::write(
        project_dir.join("validators").join("dkg_fault_mint.ak"),
        policy,
    )
    .expect("write generated digest DKG fault mint policy");

    let tests_dir = project_dir.join("validators").join("tests");
    fs::create_dir_all(&tests_dir).expect("create generated validator tests dir");
    let tests = digest_policy_tests_source(round_name, corrupted, honest);
    fs::write(tests_dir.join("dkg_fault_mint.ak"), tests)
        .expect("write generated digest DKG fault mint policy tests");
}

fn digest_policy_source(
    round_name: &str,
    corrupted: &DigestProofArtifact,
    honest: &DigestProofArtifact,
) -> String {
    let policy_id = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b";
    let benchmark_name = format!("{round_name}_corrupted_mint_benchmark");
    let reject_name = format!("{round_name}_honest_mint_rejected");

    let mut source = r#"use aiken/collection/dict
use aiken/collection/list
use aiken/crypto.{blake2b_256}
use aiken/crypto/bls12_381/scalar.{from_bytes_little_endian}
use aiken/primitive/bytearray
use cardano/address
use cardano/assets
use cardano/assets.{PolicyId, quantity_of, tokens}
use cardano/transaction.{
  Input, NoDatum, Output, OutputReference, Transaction, placeholder,
}
use proof_verifier.{verifier}

pub type FaultRedeemer {
  proof: ByteArray,
  evidence_hash: ByteArray,
  accused_pool_id: ByteArray,
}

validator dkg_fault_mint {
  mint(redeemer: FaultRedeemer, policy_id: PolicyId, self: Transaction) {
    validate_fault(redeemer, policy_id, self)
  }

  else(_) {
    fail
  }
}

pub fn validate_fault(
  redeemer: FaultRedeemer,
  policy_id: PolicyId,
  self: Transaction,
) -> Bool {
  let public_inputs = [
    from_bytes_little_endian(redeemer.evidence_hash),
    from_bytes_little_endian(redeemer.accused_pool_id),
  ]
  let token_name = fault_token_name(
    redeemer.accused_pool_id,
    redeemer.evidence_hash,
  )
  expect [Pair(minted_token_name, 1)] =
    dict.to_pairs(tokens(self.mint, policy_id))
  and {
    bytearray.length(redeemer.evidence_hash) == 32,
    bytearray.length(redeemer.accused_pool_id) == 28,
    minted_token_name == token_name,
    verifier(redeemer.proof, public_inputs),
    output_contains_token(self, policy_id, token_name),
    list.length(self.inputs) == 2,
    list.length(self.outputs) == 2,
  }
}

pub fn fault_token_name(accused_pool_id: ByteArray, evidence_hash: ByteArray) -> ByteArray {
  blake2b_256(bytearray.concat(accused_pool_id, evidence_hash))
}

fn output_contains_token(
  self: Transaction,
  policy_id: PolicyId,
  token_name: ByteArray,
) -> Bool {
  list.any(
    self.outputs,
    fn(output) { quantity_of(output.value, policy_id, token_name) == 1 },
  )
}

const policy_id =
  #"__POLICY_ID__"

const corrupted_proof =
  #"__CORRUPTED_PROOF__"

const corrupted_evidence_hash =
  #"__CORRUPTED_DIGEST__"

const corrupted_pool_id =
  #"__CORRUPTED_POOL_ID__"

const honest_proof =
  #"__HONEST_PROOF__"

const honest_evidence_hash =
  #"__HONEST_DIGEST__"

const honest_pool_id =
  #"__HONEST_POOL_ID__"

fn corrupted_redeemer() -> FaultRedeemer {
  FaultRedeemer {
    proof: corrupted_proof,
    evidence_hash: corrupted_evidence_hash,
    accused_pool_id: corrupted_pool_id,
  }
}

fn honest_redeemer() -> FaultRedeemer {
  FaultRedeemer {
    proof: honest_proof,
    evidence_hash: honest_evidence_hash,
    accused_pool_id: honest_pool_id,
  }
}

fn test_address() {
  address.from_verification_key(
    #"101112131415161718191a1b1c1d1e1f202122232425262728292a2b",
  )
}

fn output(value) -> Output {
  Output {
    address: test_address(),
    value,
    datum: NoDatum,
    reference_script: None,
  }
}

fn input(index: Int) -> Input {
  Input {
    output_reference: OutputReference {
      transaction_id: #"202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f",
      output_index: index,
    },
    output: output(assets.from_lovelace(2_000_000)),
  }
}

fn tx(redeemer: FaultRedeemer) -> Transaction {
  let token_name = fault_token_name(
    redeemer.accused_pool_id,
    redeemer.evidence_hash,
  )
  let token_output_value =
    assets.from_lovelace(1_500_000)
      |> assets.add(policy_id, token_name, 1)

  Transaction {
    ..placeholder,
    inputs: [input(0), input(1)],
    outputs: [
      output(token_output_value),
      output(assets.from_lovelace(2_000_000)),
    ],
    fee: 200_000,
    mint: assets.from_asset(policy_id, token_name, 1),
    redeemers: [],
  }
}

test __BENCHMARK_NAME__() {
  let redeemer = corrupted_redeemer()
  dkg_fault_mint.mint(redeemer, policy_id, tx(redeemer))
}

test __REJECT_NAME__() fail {
  let redeemer = honest_redeemer()
  dkg_fault_mint.mint(redeemer, policy_id, tx(redeemer))
}
"#
    .to_string();

    let replacements = [
        ("__POLICY_ID__", policy_id.to_string()),
        ("__CORRUPTED_PROOF__", hex::encode(&corrupted.proof)),
        ("__CORRUPTED_DIGEST__", bls_scalar_hex(corrupted.digest)),
        ("__CORRUPTED_POOL_ID__", hex::encode(corrupted.pool_id)),
        ("__HONEST_PROOF__", hex::encode(&honest.proof)),
        ("__HONEST_DIGEST__", bls_scalar_hex(honest.digest)),
        ("__HONEST_POOL_ID__", hex::encode(honest.pool_id)),
        ("__BENCHMARK_NAME__", benchmark_name),
        ("__REJECT_NAME__", reject_name),
    ];

    for (placeholder, value) in replacements {
        source = source.replace(placeholder, &value);
    }
    source
}

fn digest_policy_tests_source(
    round_name: &str,
    corrupted: &DigestProofArtifact,
    honest: &DigestProofArtifact,
) -> String {
    let policy = digest_policy_source(round_name, corrupted, honest);
    let (_, fixtures) = policy
        .split_once("const policy_id")
        .expect("generated policy contains fixture constants");
    let fixtures = format!("const policy_id{fixtures}")
        .replace("dkg_fault_mint.mint", "dkg_fault_mint.dkg_fault_mint.mint");

    format!(
        r#"use cardano/address
use cardano/assets
use cardano/transaction.{{Input, NoDatum, Output, OutputReference, Transaction, placeholder}}
use dkg_fault_mint
use dkg_fault_mint.{{FaultRedeemer, fault_token_name}}

{fixtures}"#
    )
}

fn bls_scalar_hex(scalar: BlsFr) -> String {
    hex::encode(scalar.to_repr())
}

fn run_aiken_check(project_dir: &Path) -> String {
    let output = Command::new("aiken")
        .arg("check")
        .arg("--deny")
        .arg("--match-tests")
        .arg("tests/dkg_fault_mint")
        .arg(".")
        .current_dir(project_dir)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .expect("aiken check should start");

    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);

    if !output.status.success() {
        print!("{stdout}");
        eprint!("{stderr}");
    } else if !stderr.trim().is_empty() {
        eprint!("{stderr}");
    }
    assert!(output.status.success(), "aiken check should pass");
    stdout.into_owned()
}

fn parse_aiken_budget(output: &str, benchmark_name: &str) -> Option<ExUnits> {
    if let Some(budget) = parse_aiken_json_budget(output, benchmark_name) {
        return Some(budget);
    }

    let lines: Vec<_> = output.lines().collect();
    for (idx, line) in lines.iter().enumerate() {
        if !line.contains(benchmark_name) {
            continue;
        }

        let window = lines[idx..lines.len().min(idx + 8)].join(" ");
        let mem = parse_metric(&window, "mem:")?.replace('_', "");
        let cpu = parse_metric(&window, "cpu:")?.replace('_', "");
        return Some(ExUnits {
            mem: mem.parse().ok()?,
            cpu: cpu.parse().ok()?,
        });
    }
    None
}

fn parse_aiken_json_budget(output: &str, benchmark_name: &str) -> Option<ExUnits> {
    let json: Value = serde_json::from_str(output).ok()?;
    let modules = json.get("modules")?.as_array()?;
    for module in modules {
        let tests = module.get("tests")?.as_array()?;
        for test in tests {
            if test.get("title")?.as_str()? != benchmark_name {
                continue;
            }

            let execution_units = test.get("execution_units")?;
            return Some(ExUnits {
                mem: execution_units.get("mem")?.as_u64()?,
                cpu: execution_units.get("cpu")?.as_u64()?,
            });
        }
    }
    None
}

fn parse_metric(text: &str, label: &str) -> Option<String> {
    let after = text.split(label).nth(1)?;
    let value: String = after
        .chars()
        .skip_while(|char| char.is_whitespace())
        .take_while(|char| char.is_ascii_digit() || *char == '_')
        .collect();
    (!value.is_empty()).then_some(value)
}

fn tx_ex_unit_limits() -> ExUnits {
    ExUnits {
        mem: env_u64("DKG_FAULT_MAX_TX_EX_MEM").unwrap_or(DEFAULT_TX_EX_UNIT_LIMITS.mem),
        cpu: env_u64("DKG_FAULT_MAX_TX_EX_CPU").unwrap_or(DEFAULT_TX_EX_UNIT_LIMITS.cpu),
    }
}

fn max_tx_size_bytes() -> usize {
    env_usize(MAX_TX_SIZE_BYTES_ENV).unwrap_or(DEFAULT_MAX_TX_SIZE_BYTES)
}

fn env_u64(name: &str) -> Option<u64> {
    let value = env::var(name).ok()?;
    Some(
        value
            .parse()
            .unwrap_or_else(|err| panic!("{name} must be an unsigned integer: {err}")),
    )
}

fn env_usize(name: &str) -> Option<usize> {
    let value = env::var(name).ok()?;
    Some(
        value
            .parse()
            .unwrap_or_else(|err| panic!("{name} must be an unsigned integer: {err}")),
    )
}

fn assert_all_within_tx_budget(reports: &[BudgetReport], limits: ExUnits) {
    let violations = reports
        .iter()
        .filter(|report| report.budget.mem > limits.mem || report.budget.cpu > limits.cpu)
        .map(|report| {
            format!(
                "{}: mem={} cpu={} limits_mem={} limits_cpu={}",
                report.name, report.budget.mem, report.budget.cpu, limits.mem, limits.cpu
            )
        })
        .collect::<Vec<_>>();

    assert!(
        violations.is_empty(),
        "on-chain DKG fault benchmarks exceed transaction ExUnit limits:\n{}",
        violations.join("\n")
    );
}

fn assert_within_tx_budget(name: &str, budget: ExUnits, limits: ExUnits) {
    assert!(
        !budget.exceeds(limits),
        "{name} exceeds transaction ExUnit limits: mem={} cpu={} limits_mem={} limits_cpu={}",
        budget.mem,
        budget.cpu,
        limits.mem,
        limits.cpu
    );
}

fn print_stats(stats: &CircuitStats, params: AxiomDkgCircuitParams) {
    println!(
        "shape: k={}, usable_rows={}, advice={:?}, lookup_advice={:?}, fixed={}, lookup_bits={:?}",
        stats.config_params.k,
        (1usize << stats.config_params.k) - params.unusable_rows,
        stats.config_params.num_advice_per_phase,
        stats.config_params.num_lookup_advice_per_phase,
        stats.config_params.num_fixed,
        stats.config_params.lookup_bits
    );
    println!("total_advice_cells: {}", stats.total_advice_cells);
    println!(
        "enabled_gate_constraints: {}",
        stats.enabled_gate_constraints
    );
    println!("total_lookup_cells: {}", stats.total_lookup_cells);
    println!("total_fixed_cells: {}", stats.total_fixed_cells);
}

fn print_keygen_times(times: &KeygenTimes) {
    println!("vk_time: {}", fmt_duration(times.vk_time));
    println!("pk_time: {}", fmt_duration(times.pk_time));
}

fn print_digest_proof_artifact(artifact: &DigestProofArtifact) {
    println!("case: {}", artifact.name);
    println!(
        "  public_instance_count: {}",
        artifact.public_instances.len()
    );
    println!("  proof_size_bytes: {}", artifact.proof.len());
    println!("  witness_time: {}", fmt_duration(artifact.witness_time));
    println!("  proof_time: {}", fmt_duration(artifact.proof_time));
    println!("  verify_time: {}", fmt_duration(artifact.verify_time));
    println!("  host_check: {}", artifact.host_check);
}

fn print_circuit_config(params: AxiomDkgCircuitParams) {
    println!(
        "circuit_config: k={}, lookup_bits={}, advice_columns={}, lookup_advice_columns={}, fixed_columns={}, limb_bits={}, num_limbs={}, window_bits={}, unusable_rows={}",
        params.degree,
        params.lookup_bits,
        params.advice_columns,
        params.lookup_advice_columns,
        params.fixed_columns,
        params.limb_bits,
        params.num_limbs,
        params.window_bits,
        params.unusable_rows
    );
}

fn print_onchain_budget(name: &str, budget: ExUnits, aiken_time: Duration) {
    println!("aiken_benchmark: {name}");
    println!("aiken_mem: {}", budget.mem);
    println!("aiken_cpu: {}", budget.cpu);
    println!("aiken_check_time: {}", fmt_duration(aiken_time));
}

fn print_full_tx_budget(
    name: &str,
    tx_size_bytes: usize,
    max_tx_size_bytes: usize,
    report: &heimdall::cardano::local_eval::LocalEvalReport,
    shape: TxShape,
    blueprint_source: &str,
    eval_time: Duration,
) {
    println!("full_tx_benchmark: {name}");
    println!("full_tx_bifrost_blueprint: {blueprint_source}");
    println!("full_tx_size_bytes: {tx_size_bytes}");
    println!("full_tx_max_size_bytes: {max_tx_size_bytes}");
    println!("full_tx_inputs: {}", shape.inputs);
    println!("full_tx_outputs: {}", shape.outputs);
    println!("full_tx_collateral_inputs: {}", shape.collateral_inputs);
    println!("full_tx_reference_inputs: {}", shape.reference_inputs);
    println!("full_tx_plutus_actions: {}", report.actions.len());
    for action in &report.actions {
        println!(
            "full_tx_action: tag={:?} index={} mem={} cpu={}",
            action.tag, action.index, action.budget.mem, action.budget.steps
        );
    }
    println!("full_tx_mem: {}", report.total.mem);
    println!("full_tx_cpu: {}", report.total.cpu);
    println!("full_tx_eval_time: {}", fmt_duration(eval_time));
}

fn fmt_duration(duration: Duration) -> String {
    format!("{:.3}s", duration.as_secs_f64())
}

#[derive(Clone, Copy)]
struct KeygenTimes {
    vk_time: Duration,
    pk_time: Duration,
}

#[derive(Clone)]
struct DigestProofArtifact {
    name: String,
    proof: Vec<u8>,
    public_instances: Vec<BlsFr>,
    digest: BlsFr,
    pool_id: [u8; 28],
    host_check: &'static str,
    witness_time: Duration,
    proof_time: Duration,
    verify_time: Duration,
}

#[derive(Clone, Copy)]
struct TxShape {
    inputs: usize,
    outputs: usize,
    collateral_inputs: usize,
    reference_inputs: usize,
}

impl DigestProofArtifact {
    fn with_digest(&self, name: &str, digest: BlsFr) -> Self {
        Self {
            name: name.to_string(),
            proof: self.proof.clone(),
            public_instances: vec![digest, self.public_instances[1]],
            digest,
            pool_id: self.pool_id,
            host_check: "redeemer evidence hash does not match proof public input",
            witness_time: Duration::ZERO,
            proof_time: Duration::ZERO,
            verify_time: Duration::ZERO,
        }
    }
}

struct BudgetReport {
    name: &'static str,
    budget: ExUnits,
}

#[derive(Clone)]
struct Round1Case {
    name: String,
    evidence: fault_evidence::Round1PokFaultEvidence,
    witness: DkgRound1PokDigestFaultWitness,
    expect_residual_matches_transcript: bool,
}

#[derive(Clone)]
struct Round2Case {
    name: String,
    evidence: fault_evidence::Round2ShareFaultEvidence,
    witness: DkgRound2ShareFaultWitness,
    expect_identity_residual: bool,
}

#[derive(Clone)]
struct EquivocationCase {
    name: String,
    evidence: fault_evidence::EquivocationEvidence,
}

fn round1_fixtures() -> Vec<Round1Case> {
    [
        ("round1-honest-pok", false, true),
        ("round1-corrupted-pok", true, false),
    ]
    .into_iter()
    .map(|(name, corrupt, expect_match)| {
        let evidence = round1_evidence(corrupt);
        let witness = evidence.witness().expect("round1 evidence witness");
        Round1Case {
            name: name.to_string(),
            evidence,
            witness,
            expect_residual_matches_transcript: expect_match,
        }
    })
    .collect()
}

fn round1_evidence(corrupt: bool) -> fault_evidence::Round1PokFaultEvidence {
    let mut rng = ChaCha20Rng::seed_from_u64(0x524f_554e_4431);
    let participant_identifier = 1u16;
    let identifier = Identifier::try_from(participant_identifier).unwrap();
    let (_secret, package) = participant::dkg_part1(identifier, 3, 2, &mut rng).unwrap();

    let (commitments, mut sigma_i) = frost_bridge::round1_fields(&package).unwrap();
    if corrupt {
        let mu: [u8; 32] = sigma_i[32..64].try_into().unwrap();
        sigma_i[32..64].copy_from_slice(&corrupt_scalar_be(&mu));
    }
    let evidence_hash = fault_evidence::round1_evidence_hash_from_fields(
        &BENCH_POOL_ID,
        participant_identifier,
        &commitments,
        &sigma_i,
    )
    .unwrap();
    let canonical_round1_bytes = canonical::round1(
        BENCH_EPOCH,
        BENCH_THRESHOLD,
        BENCH_ATTEMPT,
        &BENCH_POOL_ID,
        &commitments,
        &sigma_i,
        &evidence_hash,
    );
    let (secp, keypair, bifrost_id_pk) = accused_key(0x31);
    let payload_signature = auth::sign_payload(&secp, &keypair, &canonical_round1_bytes);

    fault_evidence::Round1PokFaultEvidence {
        epoch: BENCH_EPOCH,
        threshold: BENCH_THRESHOLD,
        attempt: BENCH_ATTEMPT,
        accused_pool_id: BENCH_POOL_ID,
        bifrost_id_pk,
        identifier: participant_identifier,
        commitments,
        sigma_i,
        payload_signature,
    }
}

fn round2_fixtures() -> Vec<Round2Case> {
    [
        ("round2-honest-share", false, true),
        ("round2-corrupted-share", true, false),
    ]
    .into_iter()
    .map(|(name, corrupt, expect_identity)| {
        let evidence = round2_evidence(corrupt);
        let witness = evidence.witness().expect("round2 evidence witness");
        Round2Case {
            name: name.to_string(),
            evidence,
            witness,
            expect_identity_residual: expect_identity,
        }
    })
    .collect()
}

fn round2_evidence(corrupt: bool) -> fault_evidence::Round2ShareFaultEvidence {
    let mut rng = ChaCha20Rng::seed_from_u64(0x524f_554e_4432);
    let ids: Vec<Identifier> = (1..=3u16)
        .map(|id| Identifier::try_from(id).unwrap())
        .collect();

    let mut round1_secrets = BTreeMap::new();
    let mut round1_packages = BTreeMap::new();
    for &id in &ids {
        let (secret, package) = participant::dkg_part1(id, 3, 2, &mut rng).unwrap();
        round1_secrets.insert(id, secret);
        round1_packages.insert(id, package);
    }

    let mut round2_packages_per_sender = BTreeMap::new();
    for &id in &ids {
        let others: BTreeMap<_, _> = round1_packages
            .iter()
            .filter(|&(&peer, _)| peer != id)
            .map(|(&peer, package)| (peer, package.clone()))
            .collect();
        let secret = round1_secrets.remove(&id).unwrap();
        let (_secret2, packages2) = participant::dkg_part2(secret, &others).unwrap();
        round2_packages_per_sender.insert(id, packages2);
    }

    let sender = ids[0];
    let recipient = ids[1];
    let recipient_index = 2u16;

    let share_bytes = round2_packages_per_sender[&sender][&recipient]
        .signing_share()
        .serialize();
    let mut share: [u8; 32] = share_bytes.as_slice().try_into().unwrap();
    if corrupt {
        share = corrupt_scalar_be(&share);
    }

    let (sender_commitments, sender_sigma) =
        frost_bridge::round1_fields(&round1_packages[&sender]).unwrap();
    let evidence_hash = fault_evidence::round2_evidence_hash_from_fields_dyn(
        &BENCH_POOL_ID,
        recipient_index,
        &sender_commitments,
        &share,
    )
    .unwrap();
    let round1_evidence_hash = fault_evidence::round1_evidence_hash_from_fields(
        &BENCH_POOL_ID,
        1,
        &sender_commitments,
        &sender_sigma,
    )
    .unwrap();
    let canonical_round1_bytes = canonical::round1(
        BENCH_EPOCH,
        BENCH_THRESHOLD,
        BENCH_ATTEMPT,
        &BENCH_POOL_ID,
        &sender_commitments,
        &sender_sigma,
        &round1_evidence_hash,
    );
    let pad = [0xA5; 32];
    let ciphertext = xor32(&share, &pad);
    let entry = canonical::ShareEntry {
        recipient_pool_id: [0x52; 28],
        recipient_identifier: u64::from(recipient_index),
        ephemeral_pk: sender_commitments[0],
        ciphertext,
        pad_commit: blake2b_256(&pad),
        evidence_hash,
    };
    let round2_canonical_bytes = canonical::round2(
        BENCH_EPOCH,
        BENCH_THRESHOLD,
        BENCH_ATTEMPT,
        &BENCH_POOL_ID,
        &[entry],
    );
    let (secp, keypair, bifrost_id_pk) = accused_key(0x32);
    let round1_signature = auth::sign_payload(&secp, &keypair, &canonical_round1_bytes);
    let round2_signature = auth::sign_payload(&secp, &keypair, &round2_canonical_bytes);

    fault_evidence::Round2ShareFaultEvidence {
        epoch: BENCH_EPOCH,
        threshold: BENCH_THRESHOLD,
        attempt: BENCH_ATTEMPT,
        accused_pool_id: BENCH_POOL_ID,
        bifrost_id_pk,
        recipient_index,
        round2_entry_index: 0,
        sender_commitments,
        canonical_round1_bytes,
        round1_signature,
        share,
        pad,
        round2_canonical_bytes,
        round2_signature,
    }
}

fn equivocation_fixture() -> EquivocationCase {
    let (secp, keypair, bifrost_id_pk) = accused_key(0x45);

    let commitments_a = [[0x02u8; 33], [0x03u8; 33]];
    let sigma_a = [0x11u8; 64];
    let evidence_hash_a = [0x44u8; 32];
    let payload_a = canonical::round1(
        BENCH_EPOCH,
        BENCH_THRESHOLD,
        BENCH_ATTEMPT,
        &BENCH_POOL_ID,
        &commitments_a,
        &sigma_a,
        &evidence_hash_a,
    );

    let commitments_b = [[0x02u8; 33], [0x04u8; 33]];
    let sigma_b = [0x22u8; 64];
    let evidence_hash_b = [0x55u8; 32];
    let payload_b = canonical::round1(
        BENCH_EPOCH,
        BENCH_THRESHOLD,
        BENCH_ATTEMPT,
        &BENCH_POOL_ID,
        &commitments_b,
        &sigma_b,
        &evidence_hash_b,
    );

    let signature_a = auth::sign_payload(&secp, &keypair, &payload_a);
    let signature_b = auth::sign_payload(&secp, &keypair, &payload_b);
    let evidence = fault_evidence::EquivocationEvidence {
        phase: fault_evidence::NamespacePhase::Round1,
        epoch: BENCH_EPOCH,
        threshold: BENCH_THRESHOLD,
        attempt: BENCH_ATTEMPT,
        accused_pool_id: BENCH_POOL_ID,
        bifrost_id_pk,
        payload_a,
        signature_a,
        payload_b,
        signature_b,
    };
    evidence.verify().expect("equivocation fixture verifies");

    EquivocationCase {
        name: "equivocation-round1".to_string(),
        evidence,
    }
}

fn corrupt_scalar_be(bytes: &[u8; 32]) -> [u8; 32] {
    be_bytes_from_fq(axiom_scalar_from_be_bytes(bytes) + Fq::from(1))
}

fn xor32(a: &[u8; 32], b: &[u8; 32]) -> [u8; 32] {
    let mut out = [0u8; 32];
    for (out, (left, right)) in out.iter_mut().zip(a.iter().zip(b.iter())) {
        *out = left ^ right;
    }
    out
}

fn accused_key(seed: u8) -> (Secp256k1<bitcoin::secp256k1::All>, Keypair, [u8; 32]) {
    let secp = Secp256k1::new();
    let secret = SecretKey::from_slice(&[seed; 32]).expect("deterministic secp secret key");
    let keypair = Keypair::from_secret_key(&secp, &secret);
    let bifrost_id_pk = keypair.x_only_public_key().0.serialize();
    (secp, keypair, bifrost_id_pk)
}
