// Generator for `tests/fixtures/cpo_trie_vectors.json` — the golden vectors that
// pin heimdall's completed-peg-outs trie encodings to the reference Scala
// implementations the on-chain validators are built from.
//
// Three things are pinned, all of them consensus-critical:
//
//   * `por_id`   = sha2_256(serialiseData(OutputReference)) — the trie KEY that
//                  Aiken's `bifrost/utils.hash_output_ref` recomputes on-chain.
//   * trie value = scriptPubKey ++ le8(amount) — the bytes `peg-out.ak`'s
//                  Complete branch rebuilds from the request datum.
//   * MPF roots  = scalus `MerklePatriciaForestry`, the same hashing the Aiken
//                  `merkle-patricia-forestry` library performs.
//
// If heimdall's Rust port ever drifts from any of these, every peg-out completion
// stops verifying — hence a vector file rather than a hand-written constant.
//
// To regenerate (scalus 1.0.0 is not on Maven Central; take the jars from a local
// binocular build's resolved classpath):
//
//   JARS=$(coursier fetch org.scalus::scalus:1.0.0 -p)
//   scala-cli run --extra-jars "$JARS" tools/GenCpoVectors.scala \
//     > tests/fixtures/cpo_trie_vectors.json
//
// Then run `cargo test cpo_trie` — the Rust side asserts against every entry.

//> using scala 3.3.8

import scalus.cardano.onchain.plutus.prelude.List as ScalusList
import scalus.crypto.trie.MerklePatriciaForestry as MPF
import scalus.uplc.builtin.{Builtins, ByteString, Data}

object GenVectors {

  def bs(hexStr: String): ByteString =
    ByteString.fromArray(hexStr.grouped(2).map(p => Integer.parseInt(p, 16).toByte).toArray)

  def outRefData(txidHex: String, index: Long): Data =
    Data.Constr(0, ScalusList.from(Seq[Data](Data.B(bs(txidHex)), Data.I(BigInt(index)))))

  def serialised(txidHex: String, index: Long): String =
    Builtins.serialiseData(outRefData(txidHex, index)).toHex

  def porId(txidHex: String, index: Long): String =
    Builtins.sha2_256(Builtins.serialiseData(outRefData(txidHex, index))).toHex

  def trieValue(spkHex: String, amount: Long): ByteString =
    bs(spkHex) ++ Builtins.integerToByteString(false, 8, BigInt(amount))

  def main(args: Array[String]): Unit = {
    val outrefs = Seq(
      ("aa" * 32, 0L),
      ("aa" * 32, 1L),
      ("00" * 32, 0L),
      ("ff" * 32, 255L),
      ("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef", 7L),
      ("9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08", 42L)
    )

    val spk1 = "5120" + "aa" * 32
    val spk2 = "0014" + "bb" * 20
    val spk3 = "76a914" + "cc" * 20 + "88ac"

    val entries = Seq(
      (porId("aa" * 32, 0L), spk1, 100000L),
      (porId("aa" * 32, 1L), spk2, 2500L),
      (porId("00" * 32, 0L), spk3, 987654321L)
    )

    def rootOf(es: Seq[(String, String, Long)]): String =
      es.foldLeft(MPF.empty)((t, e) => t.insert(bs(e._1), trieValue(e._2, e._3))).rootHash.toHex

    val sb = new StringBuilder
    sb ++= "{\n"
    sb ++= "  \"note\": \"Generated by scalus 1.0.0 (scalus.crypto.trie.MerklePatriciaForestry + Builtins.serialiseData/sha2_256/integerToByteString). Regenerate with scratchpad GenVectors.scala. Do not edit by hand.\",\n"
    sb ++= "  \"por_id\": [\n"
    sb ++= outrefs
      .map { case (t, i) =>
        s"""    { "tx_hash": "$t", "output_index": $i, "cbor": "${serialised(t, i)}", "por_id": "${porId(t, i)}" }"""
      }
      .mkString(",\n")
    sb ++= "\n  ],\n"
    sb ++= "  \"trie_value\": [\n"
    sb ++= Seq((spk1, 100000L), (spk2, 2500L), (spk3, 987654321L), (spk1, 0L))
      .map { case (s, a) =>
        s"""    { "script_pubkey": "$s", "amount": $a, "value": "${trieValue(s, a).toHex}" }"""
      }
      .mkString(",\n")
    sb ++= "\n  ],\n"
    sb ++= s"""  "empty_root": "${MPF.empty.rootHash.toHex}",\n"""
    sb ++= "  \"roots\": [\n"
    val steps = (1 to entries.length).map { n =>
      val es = entries.take(n)
      val body = es
        .map { case (k, s, a) =>
          s"""        { "por_id": "$k", "script_pubkey": "$s", "amount": $a }"""
        }
        .mkString(",\n")
      s"""    {
         |      "entries": [
         |$body
         |      ],
         |      "root": "${rootOf(es)}"
         |    }""".stripMargin
    }
    sb ++= steps.mkString(",\n")
    sb ++= "\n  ],\n"
    sb ++= s"""  "root_reversed_insert_order": "${rootOf(entries.reverse)}",\n"""
    sb ++= s"""  "commitment_prefix": "6a2543504f5231"\n"""
    sb ++= "}\n"
    println(sb.toString)
  }
}
